import type { CalculatorId } from "@/lib/calculatorsCatalog";

export type CalculatorContentBlock = {
  quick: string[];
  deepDiveTitle?: string;
  deepDive?: string[];
  howToMeasureTitle: string;
  howToMeasureSteps: string[];
  assumptionsTitle: string;
  assumptions: string[];
  buyingTipsTitle: string;
  buyingTips: string[];
  commonMistakesTitle?: string;
  commonMistakes?: string[];
  lastUpdated: string;
};

export const CALCULATOR_CONTENT_EN: Record<CalculatorId, CalculatorContentBlock> =
  {
    concrete: {
      quick: [
        "Measure slab length x width and confirm the thickness (inches or cm).",
        "Use finished (installed) dimensions, not forms that will be trimmed.",
        "Add a buffer for over-excavation, spillage, and uneven subgrade (often 5-10%).",
      ],
      deepDiveTitle: "Why thickness drives cost",
      deepDive: [
        "Concrete volume is area x thickness, so small thickness changes can add up fast on larger slabs. When you're near a delivery minimum, rounding and buffers can affect price more than the raw math.",
        "If your pour includes thickened edges, grade beams, or footings, estimate those separately and add them to the slab volume for a more reliable order.",
      ],
      howToMeasureTitle: "How to measure your slab",
      howToMeasureSteps: [
        "Split complex shapes into rectangles and add their areas.",
        "Convert thickness to feet (in / 12) or meters (cm / 100) before volume math.",
        "If edges are thickened or there are footings, estimate those separately.",
      ],
      assumptionsTitle: "Assumptions to double-check",
      assumptions: [
        "Thickness is average thickness across the whole pour (high/low spots change volume).",
        "Concrete is ordered by volume (cubic yards/meters); suppliers may have minimums.",
        "Ordering short can stop a pour; buffers are usually cheaper than a second delivery.",
      ],
      buyingTipsTitle: "Ordering tips",
      buyingTips: [
        "Confirm PSI, slump, fiber, and admixtures with your supplier before ordering.",
        "Plan a little extra for waste and wheelbarrow/pump line loss if applicable.",
        "Round up to delivery minimums and consider timing so you can place it continuously.",
      ],
      commonMistakesTitle: "Common mistakes to avoid",
      commonMistakes: [
        "Using form dimensions instead of finished dimensions (or forgetting to subtract voids).",
        "Forgetting thickened edges/footings when they're part of the same pour.",
        "Ordering with no buffer for subgrade variation; ordering short is usually the most expensive outcome.",
      ],
      lastUpdated: "Last updated: Dec 2025",
    },
    concreteBags: {
      quick: [
        "Estimate concrete volume from area and thickness (slabs, pads, small pours).",
        "Choose a bag size (80/60/50/40 lb) to convert volume to bags and round up.",
        "Add a small buffer for spillage and uneven subgrade (often 5-10%).",
      ],
      deepDiveTitle: "Bag yields vary (use the label)",
      deepDive: [
        "Bagged concrete is sold by weight, but what you need is volume. The key number is yield (cubic feet per bag), and it varies by brand, mix type, and how much water you add.",
        "For larger pours, ready-mix often becomes cheaper and more consistent than mixing many bags—your time and fatigue are real costs.",
        "If you're near a whole-bag threshold, round up. Losing a few minutes to get more bags is cheaper than a cold joint from running short mid-pour.",
      ],
      howToMeasureTitle: "How to estimate concrete bags",
      howToMeasureSteps: [
        "Measure total area (length x width) and choose the finished thickness.",
        "Convert to cubic feet and then divide by the bag yield (cubic feet per bag).",
        "Round up to whole bags and consider mixing losses and waste.",
        "If you have thickened edges or footings, estimate those separately and add them to the slab volume.",
      ],
      assumptionsTitle: "Assumptions to double-check",
      assumptions: [
        "Bag yield depends on product and mix water; use the bag label if possible.",
        "Thickness is average thickness across the pour—high/low spots change volume.",
        "For larger jobs, ready-mix may be cheaper and more consistent than bagged mix.",
      ],
      buyingTipsTitle: "Buying tips",
      buyingTips: [
        "Check the bag label for yield and recommended water—brands differ.",
        "Buy extra if you need continuous placement (you don't want to run short mid-pour).",
        "Plan mixing time, help, and tools—bagged concrete is labor-intensive.",
        "Pre-stage water, tools, and wheelbarrows—setup delays can cost you more than a few extra bags.",
      ],
      commonMistakesTitle: "Common mistakes to avoid",
      commonMistakes: [
        "Assuming all 80 lb bags have the same yield—always check the label.",
        "Forgetting that thickness is an average (low spots can add a lot of volume).",
        "Underestimating how long it takes to mix and place many bags before they start setting.",
        "Adding extra water to make mixing easier (it can weaken the final concrete).",
      ],
      lastUpdated: "Last updated: Dec 2025",
    },
    studs: {
      quick: [
        "Start with total wall length and choose a stud spacing (16\" or 24\" on center are common).",
        "Add openings (doors/windows) because headers and king/jack studs add extra lumber.",
        "Add a waste factor for bad studs, cut-offs, and layout changes (often 5-10%).",
      ],
      deepDiveTitle: "Framing varies by corners and openings",
      deepDive: [
        "Stud counts are not just length / spacing. Corners, T-walls, and openings add extra studs, and some layouts use 3-stud corners or extra blocking depending on practice and code.",
        "Use this as a planning estimate, then adjust after you finalize door/window locations and any structural requirements.",
        "If you're framing load-bearing walls, header sizing and stud packs around openings can change counts more than spacing math suggests.",
      ],
      howToMeasureTitle: "How to estimate studs",
      howToMeasureSteps: [
        "Measure the total length of walls you plan to frame (sum each wall length).",
        "Choose stud spacing based on your project and local code/practice.",
        "Add extra studs for openings and corners, then round up for waste.",
        "If you're planning plates, include top/bottom plates separately (they're often a bigger cost driver than expected).",
      ],
      assumptionsTitle: "Assumptions to double-check",
      assumptions: [
        "This is a planning estimate—real framing varies by corners, T-walls, blocking, and layout.",
        "Openings often need extra studs (king/jack), plus headers and cripples not counted here.",
        "Always follow local code and engineering requirements for structural walls.",
      ],
      buyingTipsTitle: "Buying tips",
      buyingTips: [
        "Use actual lumber dimensions and grade recommended for your project.",
        "Buy a few extra studs to cover warping and defects.",
        "If you're pricing plates, confirm whether you're buying by linear foot or by full boards.",
        "If you're framing long walls, sight down studs and set aside the worst crowns to reduce rework.",
      ],
      commonMistakesTitle: "Common mistakes to avoid",
      commonMistakes: [
        "Ignoring openings and corners (they can add more studs than spacing math suggests).",
        "Forgetting top/bottom plates and blocking when budgeting lumber.",
        "Not accounting for bad/warped studs—especially on longer walls.",
        "Assuming 24\" OC is always acceptable—many walls and finishes require 16\" OC depending on code and load.",
      ],
      lastUpdated: "Last updated: Dec 2025",
    },
    baseboardTrim: {
      quick: [
        "Start with total wall perimeter and subtract door openings.",
        "Choose a standard piece length (often 8 ft or 12 ft) to estimate how many pieces to buy.",
        "Add waste for miter cuts, corners, and defects (often 5-10%).",
      ],
      deepDiveTitle: "Corners drive waste",
      deepDive: [
        "Baseboard ordering is mostly linear feet, but the number of corners and joints determines how much cutting waste you generate.",
        "Buying a little extra from the same run can save time if you need a repair later and want the profile to match.",
        "If you're working around out-of-square rooms or wavy walls, you'll usually need more fitting and waste than the perimeter suggests.",
      ],
      howToMeasureTitle: "How to estimate baseboard and trim",
      howToMeasureSteps: [
        "Measure room perimeter (sum of all wall lengths) and subtract each door width.",
        "Decide if you're trimming closets and alcoves—include those lengths if needed.",
        "Convert total length into pieces using your chosen stock length and round up.",
        "Count inside/outside corners—more corners typically means more waste from miter cuts.",
      ],
      assumptionsTitle: "Assumptions to double-check",
      assumptions: [
        "Actual coverage depends on how you place joints and whether you scarf-joint long runs.",
        "Old houses may have out-of-square corners and require extra waste for fitting.",
        "Some trims are sold per piece; others per linear foot—use the pricing you have.",
      ],
      buyingTipsTitle: "Buying tips",
      buyingTips: [
        "Buy extra for matching color/grain and for future repairs.",
        "If you plan to paint, primed MDF is common; for stain, choose matching species.",
        "Check return policy for special-order profiles before buying extra.",
        "If you're staining, try to buy enough at once—wood color can vary between batches.",
      ],
      commonMistakesTitle: "Common mistakes to avoid",
      commonMistakes: [
        "Forgetting to subtract door openings (baseboard typically stops at casing).",
        "Underestimating waste on many corners and angled cuts.",
        "Not planning for caulk/filler/paint (the trim itself is only part of the job).",
        "Ignoring shoe molding / quarter round if your floors aren't perfectly tight to the wall.",
      ],
      lastUpdated: "Last updated: Dec 2025",
    },
    deck: {
      quick: [
        "Confirm board width (actual, not nominal) and the gap you plan to leave.",
        "Measure deck length and width using finished dimensions.",
        "Add waste for cuts and odd layouts (often 5-10%).",
      ],
      deepDiveTitle: "Board direction changes the math",
      deepDive: [
        "Decking is easier to estimate when you know board direction and whether you're adding borders or stairs. Straight installs often waste less than diagonal patterns.",
        "This calculator focuses on deck boards; framing (joists/beams/posts) and hardware should be estimated separately.",
        "For composite decking, manufacturer rules (joist spacing, gapping, hidden fasteners) can affect both quantities and cost. Always validate with the specific product guide.",
      ],
      howToMeasureTitle: "How to measure your deck",
      howToMeasureSteps: [
        "Use the finished frame size (length x width).",
        "If the deck is L-shaped, measure each rectangle and add them.",
        "Include any steps or landings you plan to deck over.",
        "If you're adding a picture-frame border, estimate border boards separately and increase waste for miter cuts.",
      ],
      assumptionsTitle: "Assumptions to double-check",
      assumptions: [
        "This estimates deck boards, not joists, beams, posts, or fasteners.",
        "Actual board coverage depends on board width and your gap spacing.",
        "Stairs, picture framing, and patterns can increase waste significantly.",
      ],
      buyingTipsTitle: "Buying tips",
      buyingTips: [
        "Confirm actual board width and recommended spacing for your material.",
        "Round up if you have stairs or many cuts, and keep a few spare boards.",
        "If matching color later matters, buy extra from the same batch when possible.",
        "Budget fasteners/clips separately—fastener choice can change cost as much as the boards on some builds.",
      ],
      commonMistakesTitle: "Common mistakes to avoid",
      commonMistakes: [
        "Using rough framing dimensions instead of finished deck dimensions.",
        "Not increasing waste for stairs, borders, or diagonal layouts.",
        "Forgetting fasteners and hardware when budgeting.",
        "Ignoring expansion/gapping guidance for the specific material (especially composites).",
      ],
      lastUpdated: "Last updated: Dec 2025",
    },
    drywall: {
      quick: [
        "Measure total wall/ceiling area, then pick sheet size (4x8, 4x10, 4x12).",
        "Add waste for cuts, outlets, and breakage (often 10-15%).",
        "Round up to whole sheets—partial sheets are not practical.",
      ],
      deepDiveTitle: "Sheet size changes seam count",
      deepDive: [
        "Larger sheets usually mean fewer seams (less finishing) but can be harder to handle and transport, especially on ceilings.",
        "Projects with many small sections and angles typically need more waste because offcuts are harder to reuse.",
        "If you're hanging ceilings, choose sheet size based on handling (lifts, help, access) as much as math—fewer seams isn't worth a dangerous install.",
      ],
      howToMeasureTitle: "How to measure for drywall",
      howToMeasureSteps: [
        "For walls: sum (wall width x height) for each wall.",
        "For ceilings: area = length x width; add any soffits separately.",
        "Convert to total square feet/meters and divide by sheet coverage.",
      ],
      assumptionsTitle: "Assumptions to double-check",
      assumptions: [
        "This estimates sheet count, not studs, mud, tape, screws, or corner bead.",
        "Ceilings and tall walls often need thicker board (confirm local code).",
        "Openings can be ignored for a rough estimate, but waste usually covers the difference.",
      ],
      buyingTipsTitle: "Buying tips",
      buyingTips: [
        "Confirm thickness (1/2\" vs 5/8\") and moisture resistance for bathrooms.",
        "Plan waste based on layout complexity and the number of openings.",
        "Consider delivery and where sheets can be staged safely (they're heavy).",
        "If you're optimizing finishing time, larger sheets can reduce seams—if you can handle them.",
      ],
      commonMistakesTitle: "Common mistakes to avoid",
      commonMistakes: [
        "Forgetting ceiling area (or underestimating it on vaulted ceilings).",
        "Ignoring finishing materials—tape, compound, screws, and corner bead add up quickly.",
        "Choosing sheet sizes that are impractical to install (leading to extra cuts and waste).",
      ],
      lastUpdated: "Last updated: Dec 2025",
    },
    drywallMudTape: {
      quick: [
        "Drywall finishing materials depend on seam length and the number of coats.",
        "Estimate seam length from area and sheet size, then convert to tape rolls.",
        "Compound usage varies by technique and product—use this as a planning estimate and confirm bag/bucket yields.",
      ],
      deepDiveTitle: "Seams and coats drive usage",
      deepDive: [
        "Tape and compound needs depend on seam length, corners, and how many coats you apply. Larger sheets can reduce seams, but real layouts (corners, openings, soffits) still add finishing work.",
        "Compound yield varies by product type and technique, so treat this as a planning estimate and confirm with the label on the exact product you'll buy.",
        "If you're aiming for a higher finish level (e.g., Level 4-5), expect more compound, sanding, and touch-up time than a basic garage finish.",
      ],
      howToMeasureTitle: "How to estimate mud and tape",
      howToMeasureSteps: [
        "Start with total drywall area you plan to finish (sq ft or m²).",
        "Choose a sheet size; larger sheets usually mean fewer seams.",
        "Set a waste factor and adjust coat/thickness assumptions if you want a tighter estimate.",
        "Add buffer for corners, patches, and repairs—these use tape and compound but don't always show up in area math.",
      ],
      assumptionsTitle: "Assumptions to double-check",
      assumptions: [
        "This uses average seam density based on sheet size; real layouts and corners can change seam length.",
        "Compound volume depends on joint width, thickness, and feathering (and your skill level).",
        "Always follow local code and product recommendations for fire-rated assemblies.",
        "Finishing level and texture plans affect compound usage (smooth walls typically need more finishing work).",
      ],
      buyingTipsTitle: "Buying tips",
      buyingTips: [
        "Buy extra tape for corners and repairs, especially for larger projects.",
        "If you're new, mix smaller batches to reduce waste and keep workability consistent.",
        "Check the bucket/bag label for yield and recommended coverage per coat.",
        "Consider corner bead, fasteners, and sanding supplies as part of the finish budget (not just mud and tape).",
      ],
      commonMistakesTitle: "Common mistakes to avoid",
      commonMistakes: [
        "Underestimating corners and repairs—tape usage is not just flat seams.",
        "Buying too little compound when you need multiple coats and feathering.",
        "Ignoring product differences (setting-type vs premix yields and behavior differ).",
        "Not planning dry time between coats (it affects your schedule more than the material cost).",
      ],
      lastUpdated: "Last updated: Dec 2025",
    },
    drywallTexture: {
      quick: [
        "Measure total wall/ceiling area you want to texture.",
        "Choose coats/passes (some textures take multiple applications).",
        "Use the product label for coverage per bag and add waste (often 5-15%).",
      ],
      deepDiveTitle: "Coverage depends on texture type",
      deepDive: [
        "Texture coverage varies a lot by the finish (knockdown, orange peel, skip trowel) and by application method (spray vs hand). Beginners usually waste more during setup and cleanup.",
        "If you need multiple passes or heavier build, multiply your area accordingly before converting to bags.",
      ],
      howToMeasureTitle: "How to measure for drywall texture",
      howToMeasureSteps: [
        "Measure total area (sq ft or m²) to be textured.",
        "Decide how many coats/passes you expect for your chosen texture.",
        "Divide (area x coats) by coverage per bag, then round up and add a buffer.",
      ],
      assumptionsTitle: "Assumptions to double-check",
      assumptions: [
        "Coverage varies by texture type (knockdown, orange peel, skip trowel) and application method.",
        "Spraying and sanding can increase waste—beginners often need more material.",
        "Treat this as a planning estimate and confirm with the exact product label.",
      ],
      buyingTipsTitle: "Buying tips",
      buyingTips: [
        "Buy enough from the same product line so color/texture matches if you patch later.",
        "Round up—running short mid-room can make blending difficult.",
        "If you're new, plan extra waste for practice and cleanup.",
      ],
      commonMistakesTitle: "Common mistakes to avoid",
      commonMistakes: [
        "Assuming one bag covers the same area for every texture type.",
        "Not accounting for multiple coats/passes when the finish requires it.",
        "Running short mid-room, which can make matching texture difficult.",
      ],
      lastUpdated: "Last updated: Jan 2026",
    },
    fence: {
      quick: [
        "Measure total fence length and confirm panel width and post spacing.",
        "Corners, ends, and gates usually require extra posts and hardware.",
        "Add waste/buffer for layout changes, cut panels, and pickets/boards if applicable (often 5-10%).",
      ],
      deepDiveTitle: "Gates and corners change counts",
      deepDive: [
        "Fence projects rarely behave like a simple straight run. Corners, ends, and gates usually need extra posts and hardware, and slopes may require stepped or racked sections.",
        "Use this as a planning estimate, then adjust after you sketch your layout and confirm post spacing and local depth requirements.",
      ],
      howToMeasureTitle: "How to measure your fence line",
      howToMeasureSteps: [
        "Measure the total run length along the fence line (not the diagonal).",
        "Mark corners and gate openings; treat each straight run separately.",
        "Confirm local requirements for post spacing and depth (frost line).",
      ],
      assumptionsTitle: "Assumptions to double-check",
      assumptions: [
        "This is a straight-run estimate; gates/corners can increase post count.",
        "Panel systems vs picket systems differ—confirm how your product is sold.",
        "Slopes may require stepping or racking, which can change counts.",
      ],
      buyingTipsTitle: "Buying tips",
      buyingTips: [
        "Confirm whether panels are 6 ft or 8 ft and match your post spacing.",
        "Plan for gate hardware and additional posts for corners/ends.",
        "Order a little extra for damaged pieces and future repairs.",
      ],
      commonMistakesTitle: "Common mistakes to avoid",
      commonMistakes: [
        "Counting posts as length / spacing without adding corners, ends, and gates.",
        "Ignoring slope and terrain changes that require different sections or extra waste.",
        "Forgetting concrete and hardware (they're often separate cost drivers).",
      ],
      lastUpdated: "Last updated: Dec 2025",
    },
    flooring: {
      quick: [
        "Measure each room (length x width) and add them for total area.",
        "Choose a waste factor based on layout (often 5-15%).",
        "Convert area to boxes using the product's coverage per box.",
      ],
      deepDiveTitle: "Waste is the real swing factor",
      deepDive: [
        "Room shape, plank direction, and obstacles can change waste far more than small area measurement errors. Many closets and small rooms often push waste higher.",
        "Always use the exact product's coverage per box and round up—partial boxes usually aren't sold.",
        "If the product might be discontinued or hard to match later, buying a little extra now can be cheaper than a future color/texture mismatch.",
      ],
      howToMeasureTitle: "How to measure flooring area",
      howToMeasureSteps: [
        "Split L-shapes into rectangles, measure each, then add them.",
        "Include closets and small areas—cuts there can increase waste.",
        "Use the manufacturer's per-box coverage (not just plank dimensions).",
      ],
      assumptionsTitle: "Assumptions to double-check",
      assumptions: [
        "Diagonal installs and patterns increase waste.",
        "Stairs require separate estimating (area/risers/treads).",
        "If you're matching later, batch differences can matter—buy extra up front.",
      ],
      buyingTipsTitle: "Buying tips",
      buyingTips: [
        "If your layout is complex, use a higher waste factor.",
        "Round up to whole boxes and keep 1-2 boxes for future repairs.",
        "Confirm underlayment, transitions, and trims—these are separate materials.",
        'Check whether your product lists "nominal" vs "actual" coverage per box; always follow the label.',
      ],
      commonMistakesTitle: "Common mistakes to avoid",
      commonMistakes: [
        "Using a low waste factor on complex layouts or diagonal installs.",
        "Not rounding up to whole boxes (leading to shortages mid-install).",
        "Forgetting underlayment, transitions, and trim in the budget.",
      ],
      lastUpdated: "Last updated: Dec 2025",
    },
    gravel: {
      quick: [
        "Measure length x width (or total area) in feet or meters.",
        "Use a realistic depth (many projects are 2-6 inches).",
        "Add a small buffer for compaction and uneven base.",
      ],
      deepDiveTitle: "Depth and compaction matter",
      deepDive: [
        "Gravel is planned by volume but often purchased by weight. Density varies by product type and moisture, so conversions differ between suppliers.",
        "Depth is the biggest swing factor; confirm whether your depth is loose depth or compacted depth and add a buffer for uneven base.",
        "If you're building a driveway or base layer, depth recommendations vary; use your local supplier's guidance for your specific aggregate and use case.",
      ],
      howToMeasureTitle: "How to measure your area",
      howToMeasureSteps: [
        "For rectangles: area = length x width. For circles: area = pi x r^2.",
        "Break irregular shapes into rectangles, add them, and round up slightly.",
        "Convert depth to feet (in / 12) or meters (cm / 100).",
      ],
      assumptionsTitle: "Assumptions to double-check",
      assumptions: [
        "Depth is average depth after grading (low spots can increase volume).",
        "Material type affects density; supplier conversions (yards -> tons) vary.",
        "Compaction can reduce loose volume; buffers help avoid a second delivery.",
      ],
      buyingTipsTitle: "Buying tips",
      buyingTips: [
        "Confirm whether your supplier sells by yards, tons, or bags.",
        "Ask for a recommended depth for your application (driveway, path, base).",
        "Round up to delivery minimums and keep a small amount for touch-ups.",
      ],
      commonMistakesTitle: "Common mistakes to avoid",
      commonMistakes: [
        "Using loose depth when you need compacted depth (or vice versa).",
        "Assuming one universal density for all gravel types.",
        "Forgetting base prep; soft subgrade can consume more material than expected.",
      ],
      lastUpdated: "Last updated: Dec 2025",
    },
    gravelTons: {
      quick: [
        "Suppliers often sell gravel by tons, but homeowners estimate by area and volume (cubic yards).",
        "The conversion depends on density, which varies by gravel type and moisture.",
        "Use a density preset or ask your supplier for their yards-to-tons conversion.",
      ],
      deepDiveTitle: "Conversions vary by supplier",
      deepDive: [
        "A yards-to-tons conversion is only as good as the density assumption. Different gravel mixes can vary enough to change your order size.",
        "If you're close to delivery minimums, rounding up to a clean order size is usually cheaper than needing a second load.",
        "If your supplier offers their own conversion table for the exact product, use it—generic density presets are a starting point, not a guarantee.",
      ],
      howToMeasureTitle: "How to convert yards to tons",
      howToMeasureSteps: [
        "Start with volume in cubic yards (or cubic meters).",
        "Pick a density preset (pea gravel, crushed stone, base rock) or enter a custom density.",
        "Convert to tons and round up to delivery minimums.",
        "If the surface isn't perfectly flat, use an average depth from multiple measurements to avoid under-ordering.",
      ],
      assumptionsTitle: "Assumptions to double-check",
      assumptions: [
        "Density varies by product, moisture, and compaction—supplier conversions may differ.",
        "Some suppliers use short tons (US), others use metric tonnes.",
        "Rounding up usually prevents shortages and extra delivery fees.",
      ],
      buyingTipsTitle: "Buying tips",
      buyingTips: [
        "Ask your supplier whether they sell by tons, yards, or both—and what conversion they use.",
        "Confirm whether you're buying the same product (pea gravel vs crushed stone vs base rock).",
        "Include a small buffer for compaction and uneven base.",
        "If you're building layers (base + top), estimate and order them separately to avoid mixing products.",
      ],
      commonMistakesTitle: "Common mistakes to avoid",
      commonMistakes: [
        "Using a generic density that doesn't match your supplier's product.",
        "Mixing short tons and metric tonnes without noticing.",
        "Ordering with no buffer for compaction and uneven base.",
        "Estimating depth from one low spot (which can over-order) instead of averaging several checks.",
      ],
      lastUpdated: "Last updated: Dec 2025",
    },
    mulch: {
      quick: [
        "Measure your bed area and pick a target depth (often 2-4 inches).",
        "Convert depth to feet/meters before volume math.",
        "Add a small buffer for settling and uneven beds.",
      ],
      deepDiveTitle: "Depth targets depend on the goal",
      deepDive: [
        "Mulch estimates depend on the depth you end up with after raking and leveling. Irregular bed edges and existing plantings can change effective area.",
        "If you're refreshing mulch, consider whether you're topping off an existing layer or removing old mulch first; your depth target changes.",
        "Color fade and settling mean \"one yard\" can look different after a few weeks; plan a little extra if you want consistent appearance across beds.",
        "If you're using mulch for weed control, depth matters more than most people expect; too thin looks fine on day one, then weeds pop quickly.",
      ],
      howToMeasureTitle: "How to measure mulch coverage",
      howToMeasureSteps: [
        "Measure each bed (length x width), add them for total area.",
        "Exclude hardscape and established groundcover you won't cover.",
        "Choose a depth based on your goal (appearance vs weed suppression).",
        "For irregular shapes, over-measure slightly instead of trying to be perfect; waste is usually cheaper than a second trip.",
      ],
      assumptionsTitle: "Assumptions to double-check",
      assumptions: [
        "Depth is average depth after raking; mulch can settle after watering.",
        "Different mulch types have different coverage per yard/bag.",
        "Sloped beds often need a bit more to look evenly covered.",
        "Edge definition (steel edging, stone borders) affects how cleanly you can spread to a consistent depth.",
      ],
      buyingTipsTitle: "Buying tips",
      buyingTips: [
        "Confirm bag size or bulk yard coverage with your supplier.",
        "Don't pile mulch against tree trunks (avoid \"mulch volcano\").",
        "Order a little extra for touch-ups and areas you may expand later.",
        "If color matching matters, buy enough at once; bags/lots can vary between shipments.",
      ],
      commonMistakesTitle: "Common mistakes to avoid",
      commonMistakes: [
        "Using an unrealistic depth (too thin for weed suppression or too thick around plants).",
        "Forgetting settling; mulch can look thinner after rain and raking.",
        "Not accounting for irregular bed edges and obstacles that change effective area.",
        "Putting mulch over weeds without prep (many weeds will grow right through if you don't clear first).",
      ],
      lastUpdated: "Last updated: Dec 2025",
    },
    mulchBags: {
      quick: [
        "Most bagged mulch is sold by cubic feet (like 2 cu ft or 3 cu ft per bag).",
        "Estimate total mulch volume from area and depth, then convert to bags and round up.",
        "Add a small buffer for settling and uneven beds (often 5-10%).",
      ],
      deepDiveTitle: "Bag size is the key input",
      deepDive: [
        "Mulch bags are labeled by volume (cubic feet or liters). Converting your bed volume to the same unit is the fastest way to get a reliable bag count.",
        "Because mulch settles after spreading and raking, a small buffer is usually cheaper than running short and mismatching color later.",
        "If you're mixing bagged mulch with bulk, treat them as separate purchases—the coverage per unit differs and it's easy to miscount.",
      ],
      howToMeasureTitle: "How to estimate mulch bags",
      howToMeasureSteps: [
        "Measure total bed area (length x width) and pick a target depth (often 2-3 inches).",
        "Convert your volume to cubic feet and divide by the bag size (cu ft per bag).",
        "Round up to whole bags and consider buying a little extra for touch-ups.",
        "If you have a lot of curves and edging, increase waste a bit—bagged mulch is harder to spread perfectly evenly.",
      ],
      assumptionsTitle: "Assumptions to double-check",
      assumptions: [
        "Bag volume is based on the label, but actual coverage can vary by product and settling.",
        "Depth is an average depth after spreading and raking.",
        "Mulch compacts after watering; a buffer helps prevent running short.",
        "Bag counts assume you spread to a consistent depth—real beds often vary by a little.",
      ],
      buyingTipsTitle: "Buying tips",
      buyingTips: [
        "Check bag size (cu ft or liters) and coverage claims on the label.",
        "If you're matching color, buy enough from the same batch when possible.",
        "Keep a few extra bags for seasonal top-ups and areas you expand later.",
        "If you're buying many bags, compare to bulk delivery cost—bulk can be much cheaper per cubic yard.",
      ],
      commonMistakesTitle: "Common mistakes to avoid",
      commonMistakes: [
        "Using the wrong bag size (2 cu ft vs 3 cu ft makes a big difference).",
        "Forgetting settling and uneven beds when choosing depth.",
        "Buying in multiple batches when color consistency matters.",
        "Underestimating labor—many bags can take longer than you expect to move and spread.",
      ],
      lastUpdated: "Last updated: Dec 2025",
    },
    sand: {
      quick: [
        "Measure total area and pick an average depth for the sand layer.",
        "Use a density preset (dry/packed/wet) to estimate weight in tons.",
        "Add a buffer for compaction, settling, and uneven base (often 5-10%).",
      ],
      howToMeasureTitle: "How to measure your area",
      howToMeasureSteps: [
        "For rectangles: area = length x width. For circles: area = pi x r^2.",
        "Break irregular shapes into rectangles and add them together.",
        "Convert depth to feet (in / 12) or meters (cm / 100) before volume math.",
        "If you're filling low spots, estimate depth from multiple checks and use an average.",
      ],
      assumptionsTitle: "Assumptions to double-check",
      assumptions: [
        "Sand density varies by moisture and how tightly it is packed.",
        "Loose sand can compact after watering or traffic, reducing installed depth.",
        "Suppliers may sell by cubic yards or by tons; conversions depend on density.",
        "Different sand types (play vs masonry vs bedding) can behave differently in compaction and drainage.",
      ],
      buyingTipsTitle: "Buying tips",
      buyingTips: [
        "Confirm sand type (play sand, masonry sand, fill sand) with your supplier.",
        "Round up to delivery minimums and keep a little extra for touch-ups.",
        "If you are leveling, plan for low spots and uneven existing grade.",
        "If sand is part of a system (pavers, turf, mortar), follow product recommendations—wrong sand can cause failures.",
      ],
      commonMistakesTitle: "Common mistakes to avoid",
      commonMistakes: [
        "Using a single depth when the surface has low spots that need more fill.",
        "Mixing up loose depth and final compacted depth.",
        "Not confirming the sand type required for your project (play vs masonry vs bedding).",
        "Assuming a single density works for wet and dry sand (moisture can change weight noticeably).",
      ],
      lastUpdated: "Last updated: Dec 2025",
    },
    paverBase: {
      quick: [
        "A paver base usually has two layers: compacted base stone + a thin bedding sand layer.",
        "Use finished (installed) area and average depths for each layer.",
        "Add a buffer for compaction, uneven subgrade, and edge cuts (often 5-10%).",
      ],
      deepDiveTitle: "Separate base stone vs bedding sand",
      deepDive: [
        "Most paver systems use a compacted base stone layer plus a thin bedding sand layer. These layers have different thickness targets and different materials.",
        "Compaction reduces loose thickness, so plan extra material and confirm recommended depths for your soil and use case (walkway vs driveway).",
      ],
      howToMeasureTitle: "How to measure for paver base",
      howToMeasureSteps: [
        "Measure the total patio/walkway area (length x width) and include any curves by splitting into rectangles.",
        "Choose base thickness based on soil and use (walkway vs patio vs driveway).",
        "Bedding sand is typically a thin layer—confirm your paver system recommendations.",
      ],
      assumptionsTitle: "Assumptions to double-check",
      assumptions: [
        "Base stone density varies by product and moisture; supplier conversions (yards <-> tons) vary.",
        "Compaction reduces loose material thickness; plan for compaction and regrading.",
        "Edging and slope/drainage can change the effective area and material needs.",
      ],
      buyingTipsTitle: "Buying tips",
      buyingTips: [
        "Confirm the correct base material (often 3/4\" minus) and bedding sand type with your local supplier.",
        "Round up to delivery minimums and plan access for a dump/pallet drop.",
        "If you have low spots, plan extra base stone to build grade before sand.",
      ],
      commonMistakesTitle: "Common mistakes to avoid",
      commonMistakes: [
        "Using bedding sand as a thick leveling layer instead of fixing the base.",
        "Not accounting for compaction (ordering only the final thickness).",
        "Skipping edging/slope planning, which can change effective area and depth.",
      ],
      lastUpdated: "Last updated: Dec 2025",
    },
    paint: {
      quick: [
        "Start with paintable wall area (square feet/meters), or measure walls and subtract big openings.",
        "Choose a realistic coverage rate and number of coats (texture and color changes matter).",
        "Add a small buffer for touch-ups, roller/brush waste, and future repairs.",
      ],
      deepDiveTitle: "Coverage depends on surface and color",
      deepDive: [
        "Most paint estimates assume a smooth, previously painted wall. Fresh drywall, heavy texture, porous surfaces, and big color changes can all reduce coverage and increase the number of coats.",
        'If you\'re switching sheen (e.g., flat to satin) or painting over patches, plan extra for touch-ups and the "extra coat you didn\'t expect."',
        "Treat primer as its own step: it can improve coverage and durability, but it still requires material and time—especially on repairs and raw drywall.",
      ],
      howToMeasureTitle: "How to measure for paint",
      howToMeasureSteps: [
        "Find wall area (per wall width x height) and add them up.",
        "Optionally subtract large windows/doors if you want a tighter estimate.",
        "Choose coats and a coverage rate based on your paint and wall texture.",
      ],
      assumptionsTitle: "Assumptions to double-check",
      assumptions: [
        "Textured walls and color changes can reduce coverage.",
        "Primer can reduce coats, but it doesn't replace paint volume.",
        "Ceilings and trim often need different paint and coverage assumptions.",
        "Cut-in work (edges, corners, trim lines) increases time and waste even if area math is correct.",
      ],
      buyingTipsTitle: "Buying tips",
      buyingTips: [
        "Buy enough from the same batch to avoid color variation.",
        "Round up if you'll do multiple coats or have a lot of cutting-in.",
        "Keep a small amount labeled for future touch-ups.",
      ],
      commonMistakesTitle: "Common mistakes to avoid",
      commonMistakes: [
        "Using footprint area instead of wall area (walls are usually much larger than the floor).",
        "Forgetting additional coats for deep colors, stains, or dramatic color changes.",
        "Not budgeting for trim/ceiling paint separately when it's a different product.",
        "Ignoring primer on patched or stained areas (it can cause flashing and uneven finish).",
      ],
      lastUpdated: "Last updated: Dec 2025",
    },
    wallpaperRolls: {
      quick: [
        "Start with total wall area you plan to cover (square feet or square meters).",
        "Subtract large openings if you want a tighter estimate, then add a waste factor.",
        "Use a roll size preset or enter your roll width and length to estimate coverage.",
      ],
      deepDiveTitle: "Patterns often require extra rolls",
      deepDive: [
        "Wallpaper is sold by roll coverage, but real installs often need extra for pattern matching, trimming, and miscuts.",
        "If your wallpaper has a repeat, the usable length per strip can drop, which increases rolls more than area math suggests.",
        "Tall walls, lots of windows/doors, and many corners usually increase waste because each new wall often needs a fresh, full-height strip.",
      ],
      howToMeasureTitle: "How to measure for wallpaper",
      howToMeasureSteps: [
        "Measure each wall width x height and add them for total wall area.",
        "Optionally subtract doors and big windows (many estimates leave them in and rely on waste).",
        "Increase waste for patterns, lots of corners, or many small wall sections.",
        "If you have a pattern repeat, use the manufacturer guidance for how many strips per roll (it's often more accurate than pure area).",
      ],
      assumptionsTitle: "Assumptions to double-check",
      assumptions: [
        "This estimates coverage by area; real installs may need extra for pattern matching and trimming.",
        "Roll sizes vary by brand and region; confirm the label for exact width and length.",
        "Always round up to whole rolls and keep extra for repairs if you may need to match dye lots later.",
        "Different papers have different install methods (paste-the-wall vs paste-the-paper); these don't change rolls but do change your prep materials and time.",
      ],
      buyingTipsTitle: "Buying tips",
      buyingTips: [
        "Buy all rolls at once when possible so the dye lot matches.",
        "If you're using patterned wallpaper, plan a higher waste factor for matching.",
        "Check whether your product is sold as single vs double rolls and use the correct coverage.",
        "Budget primer and paste separately and follow the product's recommended system for best adhesion and removability later.",
      ],
      commonMistakesTitle: "Common mistakes to avoid",
      commonMistakes: [
        "Ignoring pattern repeat and relying on pure area coverage.",
        "Mixing single vs double rolls when comparing products.",
        "Ordering from multiple dye lots when color consistency matters.",
        "Not accounting for wall height when the roll length is borderline (you may lose a whole extra strip per roll).",
      ],
      lastUpdated: "Last updated: Dec 2025",
    },
    roofing: {
      quick: [
        "Start with roof area, then add waste for valleys/hips and cut shingles.",
        "Convert to squares (100 sq ft) and then to bundles.",
        "Round up—running short mid-roof is expensive.",
      ],
      deepDiveTitle: "Roof pitch changes the math",
      deepDive: [
        "Roofing is sold by surface area, not footprint. A steeper pitch increases the true surface area you'll shingle, even if the house footprint stays the same.",
        "If you're estimating from the ground, double-check whether your inputs represent footprint dimensions or slope dimensions; mixing them is the most common source of big errors.",
        "Complex roofs also increase waste and labor. Even if area is the same, valleys, hips, and dormers can change how many bundles you actually need.",
      ],
      howToMeasureTitle: "How to measure roof area",
      howToMeasureSteps: [
        "Measure each roof plane (length x slope length), then add them.",
        "Include dormers and overhangs if they will be shingled.",
        "Use a higher waste factor for complex roofs (valleys, hips, dormers).",
      ],
      assumptionsTitle: "Assumptions to double-check",
      assumptions: [
        "Bundles per square vary by shingle type—confirm with the product label.",
        "Starter, ridge caps, and underlayment are separate material needs.",
        "Roof pitch affects true surface area vs footprint area.",
        "If local code requires ice & water shield or special underlayment, budget it separately.",
      ],
      buyingTipsTitle: "Buying tips",
      buyingTips: [
        "Confirm bundles per square and ridge cap coverage for your shingle.",
        "Order extra for cuts and future repairs (same color/batch if possible).",
        "Consider delivery placement and weather windows before ordering.",
      ],
      commonMistakesTitle: "Common mistakes to avoid",
      commonMistakes: [
        "Forgetting waste for valleys/hips, dormers, and lots of cuts on complex roofs.",
        "Ignoring starter strips and ridge caps (they're separate materials from field shingles).",
        'Assuming every shingle is "3 bundles per square"—it varies by product.',
        "Estimating from footprint only (without accounting for pitch and actual roof planes).",
      ],
      lastUpdated: "Last updated: Dec 2025",
    },
    tile: {
      quick: [
        "Measure tiled area, then add overage (waste factor) — often 10%+.",
        "Convert to boxes using the product's coverage per box.",
        "Round up to whole boxes and keep a few tiles for repairs.",
      ],
      deepDiveTitle: "Why waste factor matters",
      deepDive: [
        "Tile waste isn't just broken pieces—it's also the cuts required around edges, corners, and obstacles. Diagonal layouts, patterns, and small formats usually increase waste.",
        "If you need tiles from the same dye lot, buying the right overage up front can save you from mismatched repairs later.",
      ],
      howToMeasureTitle: "How to measure for tile",
      howToMeasureSteps: [
        "Floor: area = length x width. Walls: sum each wall area you'll tile.",
        "Subtract large openings only if you need a tighter estimate.",
        "Increase waste for diagonal layouts, patterns, and small-format tiles.",
      ],
      assumptionsTitle: "Assumptions to double-check",
      assumptions: [
        "Coverage per box varies by tile size and packaging—use label coverage.",
        "Patterns and many cuts can push waste beyond 10-15%.",
        "Mosaics and feature borders often require separate estimating.",
      ],
      buyingTipsTitle: "Buying tips",
      buyingTips: [
        "Buy extra from the same lot/dye batch for color consistency.",
        "Round up your waste factor for complex layouts or many corners.",
        "Keep a few spare tiles after installation for future repairs.",
      ],
      commonMistakesTitle: "Common mistakes to avoid",
      commonMistakes: [
        "Using a low waste factor on complex layouts (diagonal, herringbone, many corners).",
        "Forgetting to estimate mosaics/borders separately when they have different box coverage.",
        "Not keeping spare tiles for future repairs (same lot if possible).",
      ],
      lastUpdated: "Last updated: Dec 2025",
    },
    deckMud: {
      quick: [
        "Measure your deck mud area (square feet) and average thickness (inches).",
        "Add waste/overage for uneven subfloor, mixing loss, and cleanup (often 5-15%).",
        "Use a common dry pack mortar ratio (often 5:1 sand to cement) and round up.",
      ],
      deepDiveTitle: "What deck mud is (and what it isn't)",
      deepDive: [
        "Deck mud (dry pack mortar) is a sand-and-cement mix that's packed and screeded to a flat plane. It's commonly used for shower pans, tile underlayment, and patching low areas where you need a firm, slopeable bed.",
        "It's not the same as thinset, self-leveling underlayment, or concrete. The right product depends on what you're building and the thickness range you need; follow the tile system manufacturer's instructions.",
        "Quick volume rule: volume (cu ft) = area (sq ft) x thickness (in) / 12. That means 1 cu ft covers ~12 sq ft at 1\", ~6 sq ft at 2\", and ~4 sq ft at 3\" (before waste).",
        "For shower pans, slope matters. A typical slope target is about 1/4\" per foot toward the drain, so the perimeter thickness can be noticeably higher than the drain thickness on larger showers.",
      ],
      howToMeasureTitle: "How to measure for deck mud",
      howToMeasureSteps: [
        "Measure the footprint you'll fill (e.g., shower pan) and total the area.",
        "Estimate average thickness: thin edges and thicker slopes change volume.",
        "Convert area x thickness to volume, then split volume by your sand:cement ratio.",
        "If you're building slope, measure the perimeter thickness and the drain thickness, then average them for a more realistic thickness input.",
      ],
      assumptionsTitle: "Assumptions to double-check",
      assumptions: [
        "Deck mud (dry pack mortar) is mixed by volume ratios; products and techniques vary.",
        "Cement bag volume varies by brand; treat bag counts as planning estimates.",
        "If your bed is sloped (typical for showers), thickness is not uniform—use an average.",
        "Some systems use a separate waterproofing layer (liner vs bonded membrane). Follow the system instructions—layering affects thickness and materials.",
      ],
      buyingTipsTitle: "Buying tips",
      buyingTips: [
        "Buy extra sand so you can keep a consistent mix while you work.",
        "Round up cement bags—running short mid-bed can ruin the mix consistency.",
        "Confirm whether you're using masonry sand vs play sand per local practice.",
        "If you're doing a shower pan, confirm drain type and waterproofing system first—those choices often determine the correct build-up and thickness.",
      ],
      commonMistakesTitle: "Common mistakes to avoid",
      commonMistakes: [
        "Underestimating average thickness on sloped beds (perimeter and drain thickness both matter).",
        "Mixing too wet, which can reduce pack strength and make screeding harder.",
        "Switching sand types mid-job, which changes workability and consistency.",
        "Trying to use thinset as a thick build-up layer (it's not designed for that thickness range).",
      ],
      lastUpdated: "Last updated: Jan 2026",
    },
    asphaltDriveway: {
      quick: [
        "Measure total driveway area and choose an installed thickness.",
        "Asphalt is commonly ordered by weight (tons). Density varies by mix and compaction.",
        "Add a buffer for edge irregularities, tie-ins, and thickness variation (often 5-10%).",
      ],
      deepDiveTitle: "Asphalt thickness is after compaction",
      deepDive: [
        "Asphalt is typically ordered by weight, but projects are planned by area and thickness. Confirm whether your thickness target is compacted thickness and whether the job uses multiple lifts.",
        "Density varies by mix and compaction, so your contractor or supplier's conversion is usually more reliable than generic presets.",
        "Base prep is often the biggest quality driver. Even with the right tonnage, poor drainage or soft subgrade can cause rutting and cracks much sooner than expected.",
      ],
      howToMeasureTitle: "How to estimate asphalt quantity",
      howToMeasureSteps: [
        "Measure driveway area (length x width). Split curves into rectangles and add them.",
        "Convert thickness to feet (in / 12) or meters (cm / 100) before volume math.",
        "Convert volume to tons using a realistic density preset (confirm with your contractor).",
        "If you're rebuilding the driveway, estimate base gravel separately (it can exceed the asphalt material cost).",
      ],
      assumptionsTitle: "Assumptions to double-check",
      assumptions: [
        "Installed thickness can vary after compaction; base prep affects final thickness.",
        "Different asphalt mixes can have different densities; ask your supplier for a conversion.",
        "Some jobs include multiple lifts (base + surface) with different thicknesses.",
        "Edge thickness can differ from center thickness depending on how the driveway ties into lawns, sidewalks, or garage slabs.",
      ],
      buyingTipsTitle: "Buying tips",
      buyingTips: [
        "Confirm your contractor's recommended thickness and whether it's compacted thickness.",
        "Plan delivery timing—hot mix has a limited working time.",
        "Consider minimum loads and access for a dump truck to reduce handling costs.",
        "If water currently pools, fix grading and drainage before paving—material alone won't solve it.",
      ],
      commonMistakesTitle: "Common mistakes to avoid",
      commonMistakes: [
        "Using loose thickness instead of compacted thickness when converting to tons.",
        "Ignoring edge buildup and tie-ins that increase real quantity.",
        "Not rounding up to minimum loads and then needing a second delivery.",
        "Skipping base repairs (soft spots, poor drainage) and then blaming the asphalt when it fails early.",
      ],
      lastUpdated: "Last updated: Dec 2025",
    },
    boardFeet: {
      quick: [
        "Board feet is a lumber volume unit used for pricing and ordering.",
        "Use actual thickness/width (not nominal) for the most accurate estimate.",
        "Add waste for knots, defects, and cuts (often 5-10%).",
      ],
      deepDiveTitle: "Nominal vs actual size matters",
      deepDive: [
        "Board feet is a volume unit, so thickness and width must be in inches and length in feet. Using nominal sizes instead of actual dimensions can distort estimates.",
        "If you're pricing hardwood or finish lumber, plan extra for defects, cutoffs, and grain matching.",
        "If you're buying rough lumber, remember it may be surfaced (planed) down after purchase. The final thickness can change the real usable board feet.",
      ],
      howToMeasureTitle: "How board feet works",
      howToMeasureSteps: [
        "Board feet = (thickness in inches x width in inches x length in feet) / 12.",
        "Multiply by quantity, then add a waste factor if needed.",
        "If the seller prices per board foot, multiply board feet by that price.",
        "If you're mixing lengths, calculate per length group and sum them (it's easy to miscount otherwise).",
      ],
      assumptionsTitle: "Assumptions to double-check",
      assumptions: [
        "Nominal lumber sizes (e.g., 2x6) are not the same as actual dimensions.",
        "Rough-sawn lumber may be thicker and varies by mill.",
        "Some products are priced per linear foot or per piece instead of board feet.",
        "Surfacing (S2S/S4S) changes thickness and reduces the final usable size.",
      ],
      buyingTipsTitle: "Buying tips",
      buyingTips: [
        "Confirm the actual dimensions and species/grade with the supplier.",
        "For finish work, consider adding extra for grain matching and defects.",
        "Round up to whole boards and keep a little extra for future repairs.",
        "If you need wide boards, availability can be limited—call ahead and confirm stock before you design around them.",
      ],
      commonMistakesTitle: "Common mistakes to avoid",
      commonMistakes: [
        "Mixing up inches and feet in the formula (divide by 12 at the end).",
        "Using nominal sizes when the seller prices by actual dimensions.",
        "Not adding waste for defects and cutoffs, especially for finish work.",
        "Assuming rough lumber finishes at the same thickness you bought (planing reduces size).",
      ],
      lastUpdated: "Last updated: Dec 2025",
    },
    soilMix: {
      quick: [
        "Start by estimating the total soil volume (area x depth) and add a small buffer.",
        "Pick a simple mix ratio (e.g., 50/50 compost + topsoil) and adjust for your plants and drainage.",
        "If you're buying in bulk, confirm whether your supplier sells by cubic yards or cubic meters.",
      ],
      deepDiveTitle: "Mix ratios are a starting point",
      deepDive: [
        "Soil mixes are about structure and drainage, not just volume. A simple ratio (like 50/50 compost and topsoil) is a starting point—your plants, climate, and container/bed depth may need different blends.",
        "If you're buying in bulk, confirm whether the supplier sells by cubic yards or cubic meters and whether the material is screened.",
        "If your project is for a lawn vs a raised bed, the best mix can be very different. Lawns often need a different texture than vegetable beds.",
      ],
      howToMeasureTitle: "How to estimate total soil volume",
      howToMeasureSteps: [
        "Measure total area (length x width) and choose an average depth for the bed.",
        "Convert depth to feet (in / 12) or meters (cm / 100) before volume math.",
        "Add waste to cover settling, uneven beds, and rounding to delivery minimums.",
        "If you're filling multiple beds, measure each and sum volumes—depth and settling can vary per bed.",
      ],
      assumptionsTitle: "Assumptions to double-check",
      assumptions: [
        "Compost and topsoil properties vary; a 50/50 mix is a starting point, not a universal rule.",
        "Raised beds may settle after watering—buffers help avoid running short.",
        "Some mixes need amendments (perlite, peat, lime) beyond these three components.",
        "If your soil is compacted clay, improving drainage may require more than adding compost on top.",
      ],
      buyingTipsTitle: "Buying tips",
      buyingTips: [
        "Ask whether the topsoil is screened and what the compost source is.",
        "If drainage is an issue, consider adding sand or other drainage-friendly amendments.",
        "Order a little extra for topping off after the first few waterings.",
        "If you're growing vegetables, consider a soil test or local extension guidance to avoid over-amending.",
      ],
      commonMistakesTitle: "Common mistakes to avoid",
      commonMistakes: [
        "Using a deep fill mix when you only need a thin topdressing (or vice versa).",
        "Forgetting settling—beds often drop after the first few waterings.",
        "Assuming all compost/topsoil products behave the same; quality varies widely.",
        "Over-amending without a goal (too much compost can reduce structure in some soils).",
      ],
      lastUpdated: "Last updated: Dec 2025",
    },
    topsoilBags: {
      quick: [
        "Bagged topsoil is typically sold by cubic feet (or liters) per bag.",
        "Estimate total volume from area and depth, then convert to bags and round up.",
        "Add a small buffer for settling and uneven ground (often 5-10%).",
      ],
      deepDiveTitle: "Bulk is often cheaper at volume",
      deepDive: [
        "Bagged topsoil is convenient for small projects, but for larger volumes bulk delivery is usually cheaper per cubic yard and saves a lot of handling time.",
        "Depth is the biggest swing factor—measure multiple spots and use an average so you don't over- or under-order.",
        "If you're patching low spots, you can often estimate in smaller rectangles and then add a buffer. It's usually better to round up than to mix brands mid-project.",
      ],
      howToMeasureTitle: "How to estimate topsoil bags",
      howToMeasureSteps: [
        "Measure total area (length x width) and choose an average depth.",
        "Convert volume to cubic feet and divide by your bag size (cu ft per bag).",
        "Round up to whole bags and consider delivery/handling time for large projects.",
        "If you're leveling, include extra for low spots and edge feathering.",
      ],
      assumptionsTitle: "Assumptions to double-check",
      assumptions: [
        "Bag volume is based on the label, but settling and moisture can affect coverage.",
        "Depth is an average depth after spreading and leveling.",
        "For large volumes, bulk delivery can be cheaper than bagged topsoil.",
        "Topsoil quality varies widely—screening and organic content can change how it spreads and settles.",
      ],
      buyingTipsTitle: "Buying tips",
      buyingTips: [
        "Check whether you need screened topsoil and whether compost is a better fit for planting.",
        "Buy a little extra for top-offs after watering and settling.",
        "If you need consistent texture, buy the same brand/batch when possible.",
        "If you're planting, consider blending with compost rather than using pure topsoil for all beds.",
      ],
      commonMistakesTitle: "Common mistakes to avoid",
      commonMistakes: [
        "Using the wrong bag size or mixing units (liters vs cubic feet).",
        "Underestimating settling and low spots when choosing depth.",
        "Ordering bagged soil for a bulk-sized project (time and cost add up).",
        'Assuming "topsoil" is automatically good planting soil (some products are mostly fill).',
      ],
      lastUpdated: "Last updated: Dec 2025",
    },
    tileGrout: {
      quick: [
        "Grout use depends on tile size, joint width, and joint depth.",
        "Smaller tiles and wider joints use more grout per square foot.",
        "Always round up to whole bags and keep a little extra for repairs.",
      ],
      deepDiveTitle: "Joint width and tile size drive grout",
      deepDive: [
        "Grout usage depends heavily on joint width and tile size. Small tiles and wider joints create more linear footage of joints per square foot, which increases grout consumption.",
        "Product yields vary by brand and grout type (sanded/unsanded/epoxy), so use the label of the exact grout you plan to buy when possible.",
        "Cleanup technique matters too: over-washing can remove grout from joints, while late cleanup can leave haze. Both can increase rework and waste.",
      ],
      howToMeasureTitle: "How to estimate grout",
      howToMeasureSteps: [
        "Measure total tiled area and confirm tile length and width.",
        "Pick joint width and an average joint depth (often close to tile thickness).",
        "Convert the result to bags and add waste for spillage and cleanup.",
        "If you're using multiple tile sizes or patterns, estimate each area separately and sum the totals.",
      ],
      assumptionsTitle: "Assumptions to double-check",
      assumptions: [
        "Grout density and bag yields vary by product; use label info for best accuracy.",
        "Irregular tile edges and textured tiles can increase grout usage.",
        "Large-format tile with narrow joints typically uses less grout per area.",
        "Epoxy and specialty grouts have different yields and working times than cement grouts—follow the product guide.",
      ],
      buyingTipsTitle: "Buying tips",
      buyingTips: [
        "Choose sanded vs unsanded based on joint width and product recommendations.",
        "Mix small batches if you're new to grouting to reduce waste.",
        "If color matching matters, buy enough from the same lot when possible.",
        "If you plan to seal grout, verify whether your grout requires sealing (some are stain-resistant or epoxy).",
      ],
      commonMistakesTitle: "Common mistakes to avoid",
      commonMistakes: [
        "Using a joint width different from your install plan (it changes grout volume quickly).",
        "Ignoring textured/irregular tile edges that increase grout usage.",
        "Not buying enough from the same lot when color matching matters.",
        "Assuming joint depth equals tile thickness in all cases (mortar coverage and tile profile can change it).",
      ],
      lastUpdated: "Last updated: Dec 2025",
    },
    topsoil: {
      quick: [
        "Measure total area and choose an average depth for the project.",
        "Convert depth to feet or meters before calculating volume.",
        "Add a small buffer for settling, grading, and uneven areas.",
      ],
      deepDiveTitle: "Depth and leveling drive volume",
      deepDive: [
        "Topsoil projects usually fail on depth assumptions. A small change in average depth across a large area can change yardage a lot, so it helps to measure multiple spots and use an average.",
        "If you're leveling, don't base your order on the single lowest spot. Plan the average depth you'll spread, then add a buffer for feathering edges and filling low areas.",
      ],
      howToMeasureTitle: "How to measure your area",
      howToMeasureSteps: [
        "For rectangles: area = length x width. For circles: area = pi x r².",
        "For lawns, measure sections and add them for total area.",
        "Convert depth to feet (in / 12) or meters (cm / 100).",
      ],
      assumptionsTitle: "Assumptions to double-check",
      assumptions: [
        "Use average depth—topdressing and leveling often vary across the area.",
        "If you're filling low spots, include extra volume for those areas.",
        "Bulk topsoil may settle; a buffer prevents running short.",
      ],
      buyingTipsTitle: "Buying tips",
      buyingTips: [
        "Confirm whether you need screened topsoil for a smoother finish.",
        "Round up to delivery minimums and keep a small amount for touch-ups.",
        "If you add compost, adjust the mix ratio and volume accordingly.",
        "If the soil is poor, consider a compost blend rather than straight topsoil (but don't overdo organic matter for lawns).",
      ],
      commonMistakesTitle: "Common mistakes to avoid",
      commonMistakes: [
        "Estimating depth from one low spot instead of averaging multiple measurements.",
        "Forgetting settling after watering/rolling and then needing a second delivery.",
        "Assuming all topsoil is screened and easy to spread (quality varies by supplier).",
      ],
      lastUpdated: "Last updated: Dec 2025",
    },
  };


