import type { CalculatorId } from "@/lib/calculatorsCatalog";
import type { CalculatorContentBlock } from "@/lib/content/calculatorsEn";

export const CALCULATOR_CONTENT_ES: Partial<
  Record<CalculatorId, CalculatorContentBlock>
> = {
  paint: {
    quick: [
      "Empieza por el area pintable de paredes (m2 o pies2), o mide cada pared y suma.",
      "Elige una cobertura realista y el numero de manos (la textura y el cambio de color importan).",
      "Agrega un pequeno margen para retoques, desperdicio de rodillo/brocha y reparaciones futuras.",
      "Si pintas techo o molduras con otro producto, estimarlos por separado suele ser mas preciso.",
      "Considera la imprimacion como una linea aparte cuando hay panel yeso nuevo, manchas o pintura brillante.",
      "Puertas, zocalos y gabinetes consumen pintura de forma distinta al calculo por area de pared: mejor estimarlos aparte.",
    ],
    deepDiveTitle: "La cobertura depende de la superficie y del color",
    deepDive: [
      "La cifra del envase suele asumir paredes lisas y previamente pintadas. Yeso nuevo, reparaciones porosas, texturas marcadas y manchas reducen la cobertura y pueden obligar a dar mas manos.",
      "Los cambios de color grandes (oscuro a claro o viceversa) aumentan el riesgo de transparencias. Una imprimacion adecuada puede reducir manos de acabado, pero no elimina el consumo: la imprimacion tambien se compra y se aplica.",
      "Separar por tipos de superficie mejora el calculo: paredes, techo y molduras suelen usar distinta pintura (acabado y brillo). Si mezclas todo, terminas comprando de mas o te quedas corto del producto correcto.",
      "El desperdicio no es solo derrames: recortes, esquinas y mucha moldura aumentan recargas y perdida en la bandeja y rodillo. Un poco extra suele costar menos que una visita extra a mitad del trabajo.",
      "En repintados sobre semibrillo o superficies grasosas (cocina/bano), la preparacion manda: limpiar/desengrasar, lijado ligero y, si hace falta, imprimacion de adherencia. Saltarse esto puede causar pelado y volver a pintar (mas costo).",
      "Si vas a pulverizar, el uso de material sube por sobrepulverizacion y perdida en el equipo. El acabado puede ser rapido, pero el consumo no siempre es menor que rodillo/brocha (depende del proyecto).",
    ],
    howToMeasureTitle: "Como medir para pintura de paredes",
    howToMeasureSteps: [
      "Calcula el area de cada pared: ancho x alto. Suma todas las paredes del cuarto.",
      "Si quieres afinar, resta solo aberturas grandes (puertas/ventanas grandes). Muchos dejan esos huecos y el margen lo cubre.",
      "Define cuantas manos daras y si necesitas imprimacion (pared nueva, manchas, cambio de color fuerte).",
      "Elige una cobertura realista segun textura y metodo (rodillo vs spray). Si dudas, usa una cobertura conservadora.",
      "Estima el techo por separado (largo x ancho) y las molduras por separado (longitud x altura visible).",
      "Redondea a envases completos (galones/litros) y guarda una pequena cantidad etiquetada para retoques.",
    ],
    assumptionsTitle: "Supuestos a revisar",
    assumptions: [
      "Textura, porosidad y reparaciones reducen la cobertura real.",
      "La imprimacion ayuda, pero no reemplaza el volumen total de pintura.",
      "Paredes, techo y molduras suelen usar productos distintos y requieren calculos separados.",
      "Mucho recorte (esquinas, marcos, molduras) aumenta desperdicio aunque el area sea la misma.",
      "Cambios de color intensos suelen requerir mas manos o una estrategia de imprimacion (segun el caso).",
      "La cobertura del envase es orientativa; si el acabado debe quedar perfecto, conviene planear margen.",
    ],
    buyingTipsTitle: "Consejos de compra",
    buyingTips: [
      "Compra suficiente del mismo lote si el color exacto importa.",
      "Redondea hacia arriba si daras dos manos o hay mucho recorte.",
      "Compra una muestra si dudas del color: mirala con tu iluminacion real.",
      "Elige el tipo de rodillo correcto (pelo) para la textura: afecta cobertura y acabado.",
      "Planifica imprimacion para yeso nuevo, manchas y superficies brillantes.",
      "Guarda un envase pequeno para futuros retoques: el mismo producto y brillo reduce diferencias.",
    ],
    commonMistakesTitle: "Errores comunes",
    commonMistakes: [
      "Usar el area del piso en lugar del area de paredes.",
      "Asumir una sola mano cuando hay manchas, color fuerte o pared nueva.",
      "No separar techo y molduras cuando usan otro producto o brillo.",
      "No imprimar reparaciones porosas y luego ver parches visibles (flashing).",
      "Comprar herramientas baratas que dejan marcas y obligan a dar mas manos.",
      "Confiar al 100% en la cobertura del envase sin considerar textura y metodo.",
    ],
    lastUpdated: "Ultima actualizacion: ene 2026",
  },

  flooring: {
    quick: [
      "Mide el area total del piso (incluye closets si llevaran el mismo material).",
      "Agrega un factor de desperdicio antes de convertir a cajas (cortes, paredes fuera de escuadra, patrones).",
      "Convierte a cajas usando la cobertura por caja del fabricante (pies2 o m2).",
      "Redondea a cajas completas y considera 1 caja extra para reparaciones futuras.",
      "Si hay escaleras, calculalas aparte (huellas/contrahuellas) porque no siguen el mismo calculo.",
      "Comprar todo de un mismo lote ayuda a evitar variaciones de tono.",
    ],
    deepDiveTitle: "El desperdicio lo define el diseno, no solo el area",
    deepDive: [
      "Los pisos rara vez son rectangulos perfectos. Esquinas, pasillos angostos, y paredes fuera de escuadra generan cortes que aumentan el desperdicio.",
      "El sentido de instalacion y los cambios de direccion entre habitaciones tambien afectan. Alinear juntas a traves de puertas suele aumentar cortes (segun el caso).",
      "Un 5-10% suele funcionar en instalaciones rectas en espacios simples. Patrones (diagonal, espiga) y muchos recortes pueden requerir mas (segun el caso).",
      "La cobertura por caja varia. Verifica unidades (pies2 vs m2) y que sea el mismo SKU (espesor/ancho) porque la cobertura cambia entre productos.",
      "Guardar una caja sin abrir suele ser mas facil que intentar conseguir el mismo producto anos despues.",
    ],
    howToMeasureTitle: "Como medir para cajas de piso",
    howToMeasureSteps: [
      "Mide cada habitacion: largo x ancho y suma todas las areas.",
      "Resta solo areas que no se instalan (por ejemplo, bajo gabinetes fijos) si estas seguro.",
      "Elige un factor de desperdicio segun el diseno y la complejidad del espacio.",
      "Area a comprar = area total x (1 + desperdicio).",
      "Divide por la cobertura por caja y redondea hacia arriba.",
      "Si hay escalones, estima huellas/contrahuellas por separado o usa el sistema del fabricante.",
    ],
    assumptionsTitle: "Supuestos a revisar",
    assumptions: [
      "La cobertura por caja depende del producto y de la unidad (pies2 o m2).",
      "Instalaciones con muchos cortes necesitan mas desperdicio que espacios abiertos.",
      "Piezas danadas o defectuosas requieren margen.",
      "Mezclar lotes puede crear variaciones de tono visibles.",
      "Escaleras se estiman distinto al area plana.",
    ],
    buyingTipsTitle: "Consejos de compra",
    buyingTips: [
      "Compra todo a la vez si es posible para mantener lote consistente.",
      "Confirma politica de devolucion para cajas sin abrir antes de sobrecomprar.",
      "Mezcla tablas de varias cajas durante instalacion para repartir variaciones leves.",
      "Guarda una caja sin abrir en un lugar seco para reparaciones futuras.",
      "Incluye accesorios: bajoalfombra, barrera de vapor, transiciones y molduras.",
    ],
    commonMistakesTitle: "Errores comunes",
    commonMistakes: [
      "Convertir a cajas sin agregar desperdicio.",
      "Confundir pies2 con m2 en la etiqueta.",
      "No considerar pasillos, closets o areas pequenas que suman.",
      "Asumir que una escalera ya esta incluida en el area del piso.",
      "Comprar lotes distintos para completar y notar diferencia de tono.",
    ],
    lastUpdated: "Ultima actualizacion: ene 2026",
  },

  tile: {
    quick: [
      "Mide solo las superficies que realmente vas a alicatar (piso, paredes, nichos).",
      "Define el patron y el factor de merma (cortes, roturas, coincidencia de veta/patron).",
      "Convierte el area total a cajas usando la cobertura por caja del producto.",
      "Redondea a cajas completas; una caja extra suele ahorrar problemas de lote.",
      "Si tienes varios productos (mosaico, cenefas, remates), estimarlos por separado es mas fiable.",
      "En duchas, incluye muros, piso, banca y nichos: los detalles consumen material.",
    ],
    deepDiveTitle: "La merma depende de cortes y complejidad",
    deepDive: [
      "En ceramica/porcelanato, el area es solo el inicio. La merma viene de cortes al perimetro, obstaculos, roturas al cortar y piezas que no se pueden reutilizar.",
      "Un patron recto en un cuarto grande suele desperdiciar menos que diagonal, espiga u otros patrones que fuerzan mas recortes.",
      "La coincidencia de vetas o patrones puede obligarte a descartar piezas. Si el diseno exige continuidad, sube la merma (segun el caso).",
      "La cobertura por caja varía: verifica unidades (pies2 vs m2) y recuerda que molduras y mosaicos no siguen la misma cobertura.",
      "Comprar todo de una vez reduce variacion de tono. Guardar material del mismo lote ayuda en reparaciones futuras.",
    ],
    howToMeasureTitle: "Como medir para azulejo/loseta",
    howToMeasureSteps: [
      "Pisos: mide largo x ancho de cada zona y suma. Incluye closets si van con el mismo acabado.",
      "Paredes: mide cada rectangulo (ancho x alto) y suma. Agrega nichos y bancas.",
      "Resta solo aberturas grandes que no se cubriran.",
      "Elige un factor de merma segun patron y complejidad.",
      "Area a comprar = area total x (1 + merma). Divide por cobertura por caja y redondea.",
      "Estima remates y perfiles como partidas separadas.",
    ],
    assumptionsTitle: "Supuestos a revisar",
    assumptions: [
      "El patron de colocacion cambia la merma.",
      "Muchos recortes y obstaculos aumentan desperdicio.",
      "Piezas grandes en cuartos pequenos pueden aumentar sobrantes inutiles.",
      "Mosaicos y remates tienen cobertura distinta.",
      "Lotes distintos aumentan riesgo de variacion de tono/tamano.",
    ],
    buyingTipsTitle: "Consejos de compra",
    buyingTips: [
      "Compra todas las cajas del mismo lote si es posible.",
      "Redondea hacia arriba: quedarse corto retrasa la obra.",
      "Compra 1 caja extra si el producto puede descontinuarse o si quieres repuestos.",
      "Incluye adhesivo, boquilla, separadores, impermeabilizacion (duchas) y perfiles.",
      "Si hay coincidencia de veta/patron, planifica mas material y mas tiempo de seleccion.",
    ],
    commonMistakesTitle: "Errores comunes",
    commonMistakes: [
      "No incluir nichos/bancas y luego quedarse corto.",
      "Asumir 10% siempre; en diagonal o patron puede no alcanzar.",
      "Olvidar que remates y perfiles son otra linea de compra.",
      "Confundir cobertura por caja (pies2 vs m2).",
      "No guardar repuestos del mismo lote para futuras reparaciones.",
    ],
    lastUpdated: "Ultima actualizacion: ene 2026",
  },

  drywall: {
    quick: [
      "Calcula el area total a cubrir: paredes (perimetro x altura) y techo (largo x ancho) si aplica.",
      "Elige tamano de placa (4x8, 4x10, 4x12) segun manejo y cantidad de juntas.",
      "Agrega un factor de desperdicio por cortes, esquinas, soffits y errores.",
      "Redondea a placas completas; quedarse corto retrasa la obra.",
      "Confirma espesor y tipo (1/2 vs 5/8, resistente a humedad/fuego) antes de comprar.",
      "Techos suelen requerir mas margen por recortes y dificultad de instalacion.",
    ],
    deepDiveTitle: "El diseno de placas y las juntas importan",
    deepDive: [
      "El calculo por area da una base, pero la realidad depende del trazado: donde caen las juntas, cuantas tiras pequenas se generan y cuantas aberturas hay.",
      "Placas mas largas reducen juntas, pero son mas pesadas y a veces imposibles de maniobrar en escaleras o pasillos.",
      "La mayor variacion suele venir del desperdicio: esquinas, muros cortos, techos con luces/ventilaciones y recortes para instalaciones generan sobrantes inutilizables.",
      "El tipo de placa no cambia el conteo, pero si la compra: zonas humedas y techos pueden requerir placa especifica (segun codigo/estructura).",
      "Comprar 1-2 placas extra suele ser mas barato que detenerse por una sola placa.",
    ],
    howToMeasureTitle: "Como medir para placas de yeso (drywall)",
    howToMeasureSteps: [
      "Paredes: mide el perimetro de cada cuarto y multiplica por la altura. Suma todos los cuartos.",
      "Techo: mide largo x ancho de cada cuarto y suma.",
      "Agrega areas extra (soffits, columnas) como rectangulos separados.",
      "Elige tamano de placa y calcula cobertura por placa (4x8=32 pies2, 4x10=40, 4x12=48).",
      "Divide el area total entre la cobertura por placa y agrega desperdicio (10-15% segun complejidad).",
      "Redondea hacia arriba a placas completas y revisa espesor/tipo requerido.",
    ],
    assumptionsTitle: "Supuestos a revisar",
    assumptions: [
      "Aberturas grandes pueden restarse, pero muchos las dejan y lo cubre el desperdicio.",
      "Mas recortes y obstaculos requieren mayor desperdicio.",
      "El tamano de placa afecta juntas y desperdicio segun el trazado.",
      "El espesor y tipo dependen del ambiente y codigo local.",
      "Techos con muchas cajas/luces consumen mas por recortes.",
    ],
    buyingTipsTitle: "Consejos de compra",
    buyingTips: [
      "Considera alquilar un elevador de drywall para techos.",
      "Compra tornillos, cinta y compuesto como partidas separadas.",
      "Confirma el tipo exacto de placa si necesitas resistencia a humedad/fuego.",
      "Mantén placas secas y planas para evitar dano.",
      "En remodelaciones, sube el desperdicio por paredes irregulares y sorpresas.",
    ],
    commonMistakesTitle: "Errores comunes",
    commonMistakes: [
      "Olvidar el techo cuando tambien se va a cubrir.",
      "Elegir placas largas sin considerar acceso/maniobra y terminar rompiendolas.",
      "No agregar desperdicio en cuartos con muchos recortes.",
      "Comprar el espesor equivocado y crear problemas de alineacion.",
      "Subestimar el material por no incluir detalles (soffits/columnas).",
    ],
    lastUpdated: "Ultima actualizacion: ene 2026",
  },

  concrete: {
    quick: [
      "Mide largo x ancho de la losa y confirma el espesor (cm o pulgadas).",
      "Usa dimensiones terminadas (instaladas), no solo el encofrado.",
      "Agrega margen por base irregular, derrames y sobreexcavacion (a menudo 5-10%).",
      "Si hay bordes engrosados o zapatas, estimarlos aparte y sumarlos mejora la precision.",
      "En losas con pendiente, usa el espesor promedio: pequenas diferencias cambian mucho el volumen.",
      "Refuerzo y barrera de vapor no cambian el volumen, pero si el costo y la lista de materiales.",
    ],
    deepDiveTitle: "El espesor manda en el volumen",
    deepDive: [
      "El volumen es area x espesor. En una losa grande, cambiar 1/2\" puede ser mucho material y puede afectar el costo por minimos de entrega.",
      "Subrasante blanda o desnivelada puede aumentar el espesor real en zonas bajas. Compactar y nivelar reduce sorpresas.",
      "Bordes engrosados y zapatas no siguen el mismo espesor que la losa. Separarlos como volumen adicional suele dar un pedido mas confiable.",
      "Los proveedores venden por m3 o por yardas3 y hay minimos. Redondear hacia arriba suele ser mas barato que pedir una segunda carga corta.",
      "Juntas y curado no cambian el volumen, pero si la durabilidad. Planificalos desde el inicio.",
    ],
    howToMeasureTitle: "Como medir para concreto",
    howToMeasureSteps: [
      "Mide el area terminada: largo x ancho (o divide formas irregulares y suma).",
      "Convierte el espesor a la misma unidad antes de multiplicar.",
      "Volumen = area x espesor. En pendientes, usa espesor promedio (delgado+grueso)/2.",
      "Convierte a unidad de compra: m3 o yardas3 (1 yarda3 = 27 pies3).",
      "Agrega margen por desperdicio y variaciones (5-10% segun proyecto).",
      "Si hay bordes engrosados o zapatas, calcula su volumen aparte y sumalo.",
    ],
    assumptionsTitle: "Supuestos a revisar",
    assumptions: [
      "El espesor real puede variar si la base no esta bien nivelada/compactada.",
      "Pendiente implica espesor variable; usar promedio evita subestimar.",
      "Minimos de entrega y redondeos del proveedor afectan el pedido final.",
      "Bordes engrosados y zapatas no estan incluidos en un calculo simple de losa.",
      "El margen debe reflejar metodo de colocacion y accesos.",
    ],
    buyingTipsTitle: "Consejos de compra",
    buyingTips: [
      "Consulta minimo de carga y cargos por carga corta antes de decidir el margen.",
      "Planifica acceso, herramientas y mano de obra antes de que llegue el camion.",
      "Define resistencia (PSI/MPa) y consistencia con el proveedor segun uso.",
      "Considera refuerzo, barrera de vapor y juntas como partidas separadas.",
      "En clima caluroso/ventoso, planifica curado para evitar fisuras.",
    ],
    commonMistakesTitle: "Errores comunes",
    commonMistakes: [
      "No considerar pendiente o usar el espesor maximo en toda el area.",
      "Olvidar bordes engrosados/zapatas y quedarse corto.",
      "Pedir exacto sin margen y terminar con juntas frias si falta material.",
      "No revisar minimos de entrega y sorprenderse con costos.",
      "No preparar colocacion/curado y perder calidad aunque el volumen sea correcto.",
    ],
    lastUpdated: "Ultima actualizacion: ene 2026",
  },

  roofing: {
    quick: [
      "Calcula area de techo real (superficie inclinada), no solo la huella.",
      "Convierte a 'cuadrados' (100 pies2) y luego a paquetes segun el producto.",
      "Agrega desperdicio: valles, limatesas, buhardillas y penetraciones aumentan cortes.",
      "Verifica cuantos paquetes por cuadrado tiene tu teja (no siempre son 3).",
      "Lista aparte accesorios: cumbrera, inicial, membrana, borde de goteo y tapajuntas.",
      "Redondea hacia arriba: un paquete extra suele ser mas barato que parar a mitad de obra.",
    ],
    deepDiveTitle: "Pendiente y detalles cambian el pedido",
    deepDive: [
      "La huella subestima el techo en cualquier pendiente. Para un calculo confiable necesitas area de la superficie inclinada o un multiplicador de pendiente.",
      "El desperdicio depende mas de la complejidad que del area: valles y limatesas generan cortes diagonales y sobrantes.",
      "Accesorios se olvidan. Puedes tener tejas suficientes, pero si falta inicial o cumbrera el trabajo se detiene.",
      "Paquetes por cuadrado varian por marca y tipo. Confirmar especificaciones evita errores grandes.",
      "Guardar un paquete extra del mismo lote facilita reparaciones futuras.",
    ],
    howToMeasureTitle: "Como medir para tejas/asfalto",
    howToMeasureSteps: [
      "Mide cada plano del techo: largo x ancho inclinado (o calcula con pendiente).",
      "Suma el area de todos los planos e incluye voladizos si se cubren.",
      "Cuadrados = area (pies2) / 100.",
      "Agrega desperdicio segun complejidad.",
      "Convierte a paquetes usando paquetes por cuadrado del producto.",
      "Redondea y calcula accesorios por separado (cumbrera, inicial, membrana, clavos, tapajuntas).",
    ],
    assumptionsTitle: "Supuestos a revisar",
    assumptions: [
      "La pendiente aumenta el area frente a la huella.",
      "Techos complejos requieren mas desperdicio.",
      "Paquetes por cuadrado varian por producto; no asumir un numero fijo.",
      "Accesorios tienen coberturas distintas y no se derivan automaticamente del area.",
      "Minimos de compra y disponibilidad pueden afectar el redondeo.",
    ],
    buyingTipsTitle: "Consejos de compra",
    buyingTips: [
      "Verifica requisitos del fabricante para tu pendiente y sistema.",
      "Compra tejas, inicial y cumbrera del mismo sistema/linea.",
      "Planifica membranas especiales donde el codigo lo exija (segun zona).",
      "Si el color es especial, compra un paquete extra para futuras reparaciones.",
      "Revisa politica de devolucion antes de decidir el margen.",
    ],
    commonMistakesTitle: "Errores comunes",
    commonMistakes: [
      "Estimar por huella sin considerar pendiente.",
      "Olvidar desperdicio en valles/limatesas y quedarse corto.",
      "Asumir 3 paquetes por cuadrado para cualquier producto.",
      "No comprar accesorios y detener la obra.",
      "No considerar voladizos o secciones anexas del techo.",
    ],
    lastUpdated: "Ultima actualizacion: ene 2026",
  },

  gravel: {
    quick: [
      "Mide el area a cubrir y define el espesor compactado objetivo.",
      "Convierte a volumen (area x espesor) y luego a yardas3 o m3.",
      "Agrega margen por compactacion, perdida en bordes y nivelacion (segun proyecto).",
      "Si hay capas (base y acabado), calcula cada capa por separado.",
      "Pregunta la conversion del proveedor si compras por tonelada.",
      "Redondea a cargas de entrega: los minimos del camion pueden mandar mas que la matematica exacta.",
    ],
    deepDiveTitle: "Compaccion y capas cambian la cobertura real",
    deepDive: [
      "El espesor objetivo es el espesor instalado/compactado. Si el material llega suelto, su cobertura cambia al compactar. Planear margen evita quedarse corto.",
      "Caminos y entradas suelen tener capas. Mezclar todo en un solo espesor puede producir un pedido incorrecto.",
      "Bordes y zonas bajas consumen volumen extra. En superficies irregulares, el promedio de espesor es la suposicion clave.",
      "Si compras por toneladas, la densidad y humedad importan. Usar la tabla del proveedor para el producto exacto es lo mas fiable.",
      "Un pedido ligeramente superior suele ser mas barato que un segundo viaje.",
    ],
    howToMeasureTitle: "Como medir para grava",
    howToMeasureSteps: [
      "Mide el area: largo x ancho (divide formas irregulares y suma).",
      "Convierte el espesor a una unidad consistente antes de multiplicar.",
      "Volumen = area x espesor (usa espesor promedio si hay desniveles).",
      "Convierte a unidad de compra: yardas3 (pies3/27) o m3.",
      "Agrega margen por compactacion, perdida y nivelacion.",
      "Si hay capas, repite por cada capa y suma.",
    ],
    assumptionsTitle: "Supuestos a revisar",
    assumptions: [
      "El espesor objetivo suele ser compactado, no suelto.",
      "Capas multiples deben estimarse por separado.",
      "La conversion a toneladas varía por material y humedad.",
      "Areas irregulares requieren un espesor promedio realista.",
      "Los bordes y la contencion afectan la perdida lateral.",
    ],
    buyingTipsTitle: "Consejos de compra",
    buyingTips: [
      "Confirma el tipo de grava (base triturada vs decorativa) y la gradacion.",
      "Pregunta conversion a toneladas para ese producto especifico.",
      "Planifica compactacion por capas y renta de compactador si aplica.",
      "Considera geotextil/separador si el suelo es blando (segun caso).",
      "Asegura acceso para entrega y espacio para acopiar.",
    ],
    commonMistakesTitle: "Errores comunes",
    commonMistakes: [
      "Usar espesor suelto cuando el objetivo es compactado.",
      "No calcular capas por separado y terminar con base insuficiente.",
      "No considerar zonas bajas y pedir exacto.",
      "Usar densidad generica para toneladas sin confirmarla.",
      "Olvidar la contencion de bordes y perder material hacia los lados.",
    ],
    lastUpdated: "Ultima actualizacion: ene 2026",
  },

  topsoil: {
    quick: [
      "Mide el area a cubrir y define el espesor promedio (nivelacion vs relleno).",
      "Convierte area x espesor a volumen y luego a yardas3 o m3.",
      "Agrega margen por asentamiento, zonas bajas y perdida durante extendido.",
      "Nivelar cesped suele ser capa delgada + extra en depresiones: estima ambas partes.",
      "Si compras en sacos, usa el volumen del saco (pies3 o litros), no el peso.",
      "La calidad importa: tierra cernida se extiende mejor que relleno con piedras (segun uso).",
    ],
    deepDiveTitle: "La profundidad promedio es la decision clave",
    deepDive: [
      "La tierra se vende por volumen, pero se mide por area. Pequenos cambios de profundidad cambian mucho el pedido.",
      "En nivelacion, el error tipico es usar la profundidad maxima en toda el area. Una capa fina general + volumen extra en zonas bajas suele ser mas realista.",
      "La tierra se asienta con el riego y la lluvia. Un margen pequeno evita terminar con zonas delgadas.",
      "Para jardineria, una mezcla con compost puede ser mejor que 'topsoil' generico (segun objetivo).",
      "Si el problema es drenaje, la forma (pendiente) importa mas que el volumen.",
    ],
    howToMeasureTitle: "Como medir para tierra vegetal (topsoil)",
    howToMeasureSteps: [
      "Mide el area y divide formas irregulares en rectangulos si hace falta.",
      "Define una profundidad promedio realista segun el objetivo.",
      "Convierte profundidad a unidad consistente antes de multiplicar.",
      "Volumen = area x profundidad.",
      "Convierte a yardas3 (pies3/27) o m3, o a sacos usando volumen por saco.",
      "Agrega margen por asentamiento y zonas bajas, luego redondea.",
    ],
    assumptionsTitle: "Supuestos a revisar",
    assumptions: [
      "Usar maximo en todo el terreno sobreestima; usa promedio.",
      "El material se asienta tras lluvia/riego.",
      "Zonas bajas y bordes consumen volumen extra.",
      "Bolsas se convierten por volumen, no por peso.",
      "El material correcto depende del uso (plantar vs rellenar).",
    ],
    buyingTipsTitle: "Consejos de compra",
    buyingTips: [
      "Confirma si el material es cernido para mejor acabado.",
      "Planifica acceso de entrega y donde descargar.",
      "Si necesitas elevar mucho, considera compactar por capas.",
      "Compra un poco extra para retoques despues de la primera lluvia.",
      "Para nivelacion de cesped, una mezcla arena/tierra puede facilitar extendido (segun caso).",
    ],
    commonMistakesTitle: "Errores comunes",
    commonMistakes: [
      "Usar profundidad maxima para todo y pedir de mas.",
      "Olvidar asentamiento y pedir exacto.",
      "Asumir volumen en sacos sin leer etiqueta.",
      "Elegir material de baja calidad para un acabado que requiere cernido.",
      "Intentar arreglar drenaje solo con volumen, sin plan de pendiente.",
    ],
    lastUpdated: "Ultima actualizacion: ene 2026",
  },

  mulch: {
    quick: [
      "Mide el area de las camas y decide la profundidad objetivo.",
      "Convierte area x profundidad a volumen y luego a yardas3 o a sacos.",
      "Mantén el mulch mas delgado cerca de troncos y coronas de plantas.",
      "Agrega margen por asentamiento y redistribucion al rastrillar.",
      "Si solo renuevas, a veces basta una capa delgada en vez de 3\" en todo.",
      "Compra todo a la vez si el color importa: los lotes pueden variar.",
    ],
    deepDiveTitle: "Profundidad = volumen (y salud de plantas)",
    deepDive: [
      "El mulch se aplica por area y profundidad. Duplicar profundidad duplica volumen, asi que revisa el numero antes de ordenar.",
      "Evita apilar contra troncos: puede retener humedad y causar pudricion o plagas (segun caso).",
      "El mulch se asienta con la lluvia. Un margen pequeno ayuda a lograr una cobertura pareja.",
      "En pendientes puede migrar. Bordes y mantenimiento ayudan a mantener espesor.",
      "Mulch no es material de nivelacion: corrige con tierra primero si necesitas subir o rellenar.",
    ],
    howToMeasureTitle: "Como medir para mulch",
    howToMeasureSteps: [
      "Mide el area total de camas y suma secciones.",
      "Elige profundidad objetivo segun proposito.",
      "Convierte pulgadas a pies (in/12) o a metros.",
      "Volumen = area x profundidad.",
      "Convierte a yardas3 (pies3/27) o a sacos por volumen.",
      "Agrega margen por asentamiento y bordes, luego redondea.",
    ],
    assumptionsTitle: "Supuestos a revisar",
    assumptions: [
      "Pequenos cambios de profundidad cambian mucho el volumen.",
      "El mulch se asienta; el volumen instalado puede ser menor que el entregado.",
      "No se debe acumular contra troncos/coronas.",
      "En pendientes puede haber perdida por desplazamiento.",
      "Bolsas se convierten por volumen, no por peso.",
    ],
    buyingTipsTitle: "Consejos de compra",
    buyingTips: [
      "Compra un poco extra para retoques.",
      "Confirma unidades de bolsa (pies3 o litros).",
      "Compra en un solo pedido para minimizar diferencias de color.",
      "Prepara la cama (deshierbe y borde) para que la profundidad sea efectiva.",
      "Planifica descarga y traslado segun cantidad.",
    ],
    commonMistakesTitle: "Errores comunes",
    commonMistakes: [
      "Confundir 2\" con 4\" y duplicar el pedido sin querer.",
      "Hacer 'volcan de mulch' contra troncos.",
      "Usar mulch para corregir desniveles en vez de tierra.",
      "No considerar asentamiento y quedar con zonas delgadas.",
      "Comprar en lotes distintos y notar diferencia de color.",
    ],
    lastUpdated: "Ultima actualizacion: ene 2026",
  },

  fence: {
    quick: [
      "Empieza con un plano: longitud total, esquinas, terminales y ubicacion de portones.",
      "Define el tipo de cerca y la separacion de postes (comun: 6-8 pies).",
      "Cuenta postes especiales (esquinas, terminales y porton) aparte de postes de linea.",
      "Los postes de porton suelen ser mas fuertes y pueden requerir mas concreto (segun peso).",
      "En pendientes, la cerca puede ir escalonada: eso cambia cortes y materiales.",
      "Verifica profundidad de helada y normas locales para hoyos y concreto.",
    ],
    deepDiveTitle: "Postes y geometria definen el material",
    deepDive: [
      "Muchas estimaciones fallan por subcontar postes. Esquinas y portones requieren postes dedicados y a menudo mas robustos.",
      "La separacion real muchas veces la dicta el panel prefabricado. Forzar otra separacion crea cortes y desperdicio.",
      "Terreno inclinado cambia el plan: una cerca escalonada puede usar mas postes y mas piezas cortas.",
      "La durabilidad depende de la instalacion: hoyos a profundidad adecuada, alineacion y buen drenaje.",
      "Viento y altura pueden requerir postes mas grandes y refuerzos (segun codigo).",
    ],
    howToMeasureTitle: "Como medir y planificar una cerca",
    howToMeasureSteps: [
      "Traza el recorrido y divide en tramos rectos entre esquinas/portones/terminales.",
      "Mide la longitud de cada tramo.",
      "Elige separacion de postes segun el tipo de cerca o el ancho del panel.",
      "Por tramo: calcula espacios y postes = espacios + 1 (sin duplicar postes compartidos).",
      "Agrega postes de porton y postes terminales donde corresponda.",
      "Convierte a materiales: paneles o estacas, rieles, postes, concreto y herrajes.",
    ],
    assumptionsTitle: "Supuestos a revisar",
    assumptions: [
      "Paneles prefabricados dictan separacion; no siempre es flexible.",
      "Esquinas y portones requieren postes especiales (mas grandes/profundos).",
      "Pendientes pueden aumentar postes y cortes.",
      "Profundidad de hoyo depende de heladas y normas locales.",
      "Herrajes dependen del peso y tipo de porton.",
    ],
    buyingTipsTitle: "Consejos de compra",
    buyingTips: [
      "Confirma ancho real de paneles y separacion on-center.",
      "Elige postes de porton adecuados al peso (madera mas grande o metal).",
      "Compra herrajes completos del porton y refuerzos anti-caida.",
      "Planifica concreto y materiales de drenaje segun practica local.",
      "Compra tornillos/piezas extra: se pierden y se rompen.",
    ],
    commonMistakesTitle: "Errores comunes",
    commonMistakes: [
      "No contar postes de esquina/porton como postes dedicados.",
      "Asumir separacion uniforme y luego descubrir que los paneles no encajan.",
      "Ignorar pendiente y ubicar mal los escalones.",
      "No verificar profundidad de helada y tener postes que se mueven.",
      "Subestimar herrajes del porton y detener la instalacion por piezas faltantes.",
    ],
    lastUpdated: "Ultima actualizacion: ene 2026",
  },

  wallpaperRolls: {
    quick: [
      "Mide el ancho y alto de cada pared y suma el area (o usa perimetro x altura).",
      "Resta solo aberturas grandes si quieres afinar; si no, deja un margen mayor.",
      "Convierte area a rollos usando la cobertura efectiva por rollo (segun largo, ancho y repeticion del patron).",
      "Si hay repeticion de patron (pattern repeat), la cobertura real baja y el desperdicio sube.",
      "Redondea a rollos completos y compra todos del mismo lote.",
      "Si hay muchas paredes pequenas, recortes y esquinas, planifica mas desperdicio (segun el caso).",
    ],
    deepDiveTitle: "La repeticion del patron cambia la cobertura",
    deepDive: [
      "La etiqueta del rollo indica largo y ancho, pero la cobertura efectiva depende de como cae el patron. Con repeticion, desperdicias material para alinear el dibujo en cada tira.",
      "La altura de pared manda: si tus paredes son altas, obtienes menos tiras por rollo. Eso puede cambiar el pedido mas que el area total.",
      "El desperdicio aumenta con esquinas, recortes alrededor de puertas/ventanas y paredes cortas donde no puedes reutilizar bien los sobrantes.",
      "Asegurate de comparar cobertura real (m2/pies2) y no solo la palabra 'rollo'.",
      "Comprar todos los rollos juntos reduce diferencias de tono y evita quedarte corto con el mismo lote.",
    ],
    howToMeasureTitle: "Como medir para papel tapiz",
    howToMeasureSteps: [
      "Mide alto de pared (piso a techo) y el ancho de cada pared.",
      "Calcula area total o usa perimetro x altura para un cuarto rectangular.",
      "Resta aberturas grandes solo si buscas precision fina.",
      "Verifica largo/ancho del rollo y la repeticion del patron (si aplica).",
      "Convierte a rollos segun tiras por rollo y cobertura efectiva.",
      "Redondea hacia arriba y agrega margen si hay patron o muchas interrupciones.",
    ],
    assumptionsTitle: "Supuestos a revisar",
    assumptions: [
      "Altura de pared determina cuantas tiras salen por rollo.",
      "Repeticion de patron reduce cobertura y aumenta desperdicio.",
      "Ventanas/puertas pequenas suelen quedar dentro del margen.",
      "Paredes cortas y muchos recortes aumentan desperdicio.",
      "Unidades y tipo de rollo dependen del producto.",
    ],
    buyingTipsTitle: "Consejos de compra",
    buyingTips: [
      "Compra todos los rollos del mismo lote para evitar variacion de color.",
      "Si hay patron, compra un poco extra: es mas facil devolver un rollo sin abrir que conseguir el mismo lote despues.",
      "Confirma el tipo de papel (vinilo, no tejido) porque cambia el adhesivo y el metodo de instalacion.",
      "Compra adhesivo y herramientas adecuadas (cuchilla, regla, cepillo/rodillo de alisado).",
      "Si dudas del patron o color, compra una muestra y pruebala con tu iluminacion.",
      "Planea paredes de acento por separado si no cubres todo el cuarto.",
    ],
    commonMistakesTitle: "Errores comunes",
    commonMistakes: [
      "Ignorar repeticion de patron y quedarse corto.",
      "Usar area del piso en vez de area de paredes.",
      "No medir altura real (molduras, techos inclinados) y subestimar.",
      "Comprar rollos de lotes distintos y notar diferencia de tono.",
      "No planear recortes en esquinas y alrededor de puertas/ventanas.",
    ],
    lastUpdated: "Ultima actualizacion: ene 2026",
  },

  deck: {
    quick: [
      "Define dimensiones del deck y la altura: eso determina estructura y materiales.",
      "Calcula area de la tarima y agrega desperdicio por cortes y patrones.",
      "Cuenta viguetas (joists) segun separacion on-center y ancho del deck.",
      "Incluye vigas, postes y cimentaciones como partidas separadas.",
      "Planea barandales y escaleras aparte: consumen mucho material y herrajes.",
      "Confirma normativa local (cargas, anclajes, profundidad) (segun zona).",
    ],
    deepDiveTitle: "La estructura manda el costo",
    deepDive: [
      "Un deck no es solo tablas. La estructura (viguetas, vigas, postes y cimentaciones) depende de luces, altura y carga; pequenos cambios pueden cambiar el conteo de piezas y conectores.",
      "El desperdicio de tarima depende del patron: diagonal o bordes decorativos generan mas cortes. Un deck recto simple suele desperdiciar menos.",
      "Barandales y escaleras a menudo cuestan tanto como el piso en materiales. Planificalos desde el inicio para no subestimar.",
      "La durabilidad depende de detalles: drenaje, separacion entre tablas, fijaciones correctas y proteccion de madera.",
      "En tarimas compuestas (composite), revisa separaciones y sistema de fijacion recomendado; el movimiento termico cambia el plan (segun producto).",
    ],
    howToMeasureTitle: "Como medir un deck",
    howToMeasureSteps: [
      "Mide largo x ancho para el area de tarima.",
      "Define direccion de tablas y patron (recto vs diagonal).",
      "Elige separacion de viguetas segun el material (p. ej., 12\" o 16\" OC segun producto).",
      "Calcula viguetas segun ancho y separacion, y su longitud segun el diseno.",
      "Calcula vigas y postes segun luces y puntos de apoyo.",
      "Agrega partidas para barandal, escaleras, herrajes, tornillos y anclajes.",
    ],
    assumptionsTitle: "Supuestos a revisar",
    assumptions: [
      "Separacion de viguetas depende del material de tarima y del patron.",
      "Altura del deck cambia anclajes, postes y barandal requerido.",
      "Escaleras y barandales requieren estimacion separada.",
      "Desperdicio sube con patrones y bordes.",
      "Normas locales pueden exigir detalles especificos.",
    ],
    buyingTipsTitle: "Consejos de compra",
    buyingTips: [
      "Compra conectores para exterior y herrajes resistentes a corrosion.",
      "Confirma fijaciones compatibles (tornillos o clips) con la tarima elegida.",
      "Incluye un poco extra de tarima para cortes y reparaciones futuras.",
      "Revisa distancia entre apoyos recomendada por el fabricante.",
      "Planifica drenaje y proteccion de madera si aplica.",
      "Verifica politica de devolucion antes de decidir el margen.",
    ],
    commonMistakesTitle: "Errores comunes",
    commonMistakes: [
      "Estimar solo tablas y olvidar estructura y herrajes.",
      "Usar separacion de viguetas incorrecta para el tipo de tarima.",
      "Olvidar barandales/escaleras y subestimar presupuesto.",
      "No planear drenaje y separacion entre tablas.",
      "No considerar altura y normativa local para anclajes y barandal.",
    ],
    lastUpdated: "Ultima actualizacion: ene 2026",
  },

  deckMud: {
    quick: [
      "Define el area a cubrir y el espesor promedio (por ejemplo, base de ducha con pendiente).",
      "Convierte area x espesor a volumen y luego a sacos segun rendimiento por bolsa.",
      "La pendiente cambia el espesor: usa espesor promedio para una estimacion realista.",
      "Si hay bordes altos o desniveles, estima esas zonas aparte y suma.",
      "Compra un margen: mezclar de nuevo por falta de material rompe el ritmo de trabajo.",
      "Considera desperdicio y limpieza de cubetas/herramientas en el calculo.",
    ],
    deepDiveTitle: "Espesor promedio = cantidad real",
    deepDive: [
      "El deck mud (dry pack) se estima por volumen. En duchas con pendiente, el espesor no es uniforme: el promedio entre el punto mas delgado y el mas grueso suele ser mas confiable.",
      "La mezcla se trabaja en un tiempo limitado. Quedarte corto puede obligarte a parar y mezclar otra tanda, lo que afecta calidad y pendiente.",
      "El rendimiento por bolsa varía por marca y consistencia. Usa el dato del fabricante si lo tienes y agrega margen por desperdicio.",
      "Pequenos detalles consumen material: bordes, bancos, nichos o zonas de reparacion.",
      "Si el proyecto requiere impermeabilizacion, planifica el sistema completo; el deck mud es solo una parte (segun metodo).",
    ],
    howToMeasureTitle: "Como medir deck mud",
    howToMeasureSteps: [
      "Mide el area en pies2 o m2 de la zona a cubrir.",
      "Define espesor minimo y maximo si hay pendiente.",
      "Usa espesor promedio: (min + max) / 2.",
      "Volumen = area x espesor (con unidades consistentes).",
      "Convierte a sacos usando rendimiento por bolsa del producto.",
      "Agrega margen por desperdicio y por ajustes de pendiente en obra.",
    ],
    assumptionsTitle: "Supuestos a revisar",
    assumptions: [
      "Pendiente significa espesor variable; promedio evita subestimar.",
      "Rendimiento por bolsa depende del producto y de la mezcla.",
      "Desperdicio y limpieza consumen material real.",
      "Detalles y reparaciones locales aumentan volumen.",
      "El sistema de impermeabilizacion puede requerir capas adicionales (segun metodo).",
    ],
    buyingTipsTitle: "Consejos de compra",
    buyingTips: [
      "Compra suficientes sacos para completar el trabajo en una sola jornada.",
      "No asumas que todas las marcas rinden igual; revisa la etiqueta.",
      "Prepara herramientas y el sitio para trabajar rapido.",
      "Planea agua limpia y medicion consistente para mantener mezcla uniforme.",
      "Si hay membrana o imprimaciones, incluyelas en la lista de compra.",
      "Si dudas del volumen, compra un poco extra para no cortar el trabajo.",
    ],
    commonMistakesTitle: "Errores comunes",
    commonMistakes: [
      "Estimar con espesor minimo y olvidar el espesor en la zona alta.",
      "No usar el rendimiento real del producto y quedarse corto.",
      "Mezclar tandas con consistencias distintas y crear puntos debiles.",
      "No preparar el sitio y perder tiempo mientras la mezcla se seca.",
      "Olvidar desperdicio por limpieza y ajuste de pendiente.",
    ],
    lastUpdated: "Ultima actualizacion: ene 2026",
  },

  paverBase: {
    quick: [
      "Mide el area total del proyecto y define profundidad de base compactada.",
      "Estima por capas: base granular + cama de arena (y juntas aparte).",
      "Convierte volumen a yardas3/m3 y agrega margen por compactacion y bordes.",
      "Incluye extension de base mas alla del borde de los adoquines (segun diseno).",
      "Si el terreno es blando, considera geotextil/separador (segun caso).",
      "Planea confinamiento de borde: sin borde, los adoquines se abren y se hunden.",
    ],
    deepDiveTitle: "La base es el exito del adoquin",
    deepDive: [
      "La base (piedra triturada) se coloca en capas y se compacta. Si ordenas solo el espesor final, puedes quedarte corto porque la compactacion reduce volumen.",
      "La cama de arena no es para corregir desniveles grandes. Si necesitas nivelar, corrige con la base, no con arena. Arena demasiado gruesa se mueve y causa hundimientos.",
      "La base normalmente se extiende mas alla del borde del adoquin para soporte. No olvides ese extra cuando calcules area.",
      "Los bordes (edge restraint) son parte estructural. Sin borde, la carga lateral hace que los adoquines se separen y pierdan nivel.",
      "Drenaje y pendiente importan tanto como el volumen. Una buena base falla si el agua queda atrapada (segun sitio).",
    ],
    howToMeasureTitle: "Como medir base para adoquines",
    howToMeasureSteps: [
      "Mide el area del patio/camino incluyendo bordes y extensiones planificadas.",
      "Define profundidad compactada de base (segun uso y suelo).",
      "Convierte profundidad a unidad consistente y calcula volumen = area x profundidad.",
      "Convierte a yardas3 (pies3/27) o m3.",
      "Agrega margen por compactacion, perdidas y nivelacion.",
      "Estima arena de cama y arena de juntas como partidas separadas.",
    ],
    assumptionsTitle: "Supuestos a revisar",
    assumptions: [
      "Profundidad objetivo suele ser compactada.",
      "Base puede extenderse mas alla del borde del adoquin.",
      "Suelo blando puede requerir mas base o geotextil.",
      "Arena de cama no debe usarse para grandes correcciones.",
      "Pendiente/drenaje determinan durabilidad (segun sitio).",
    ],
    buyingTipsTitle: "Consejos de compra",
    buyingTips: [
      "Confirma el tipo de base recomendado localmente.",
      "Planifica compactador de placa y trabaja por capas.",
      "Compra borde/estacas/adhesivo de borde si aplica.",
      "Compra un poco extra de base para ajustes y bordes.",
      "Si usaras arena polimerica, revisa cobertura y condiciones de clima seco.",
      "Asegura acceso para entrega y espacio para acopio.",
    ],
    commonMistakesTitle: "Errores comunes",
    commonMistakes: [
      "Usar arena de cama como capa gruesa de nivelacion.",
      "Olvidar compactacion y ordenar solo el espesor final.",
      "No incluir extension de base mas alla del borde.",
      "No instalar borde y ver que el adoquin se abre con el tiempo.",
      "Ignorar drenaje y pendiente, causando agua estancada y hundimientos.",
    ],
    lastUpdated: "Ultima actualizacion: ene 2026",
  },

  sand: {
    quick: [
      "Define el uso (cama de adoquin, relleno, mezcla, o sandbox): cambia densidad y necesidad.",
      "Mide area y espesor objetivo, luego convierte a volumen.",
      "Convierte volumen a yardas3/m3 o a bolsas segun el proveedor.",
      "Agrega margen por asentamiento, desperdicio y nivelacion.",
      "Si la arena va bajo adoquines, no la uses para corregir desniveles grandes.",
      "Si compras por tonelada, confirma densidad con tu proveedor.",
    ],
    deepDiveTitle: "Arena no es una sola cosa",
    deepDive: [
      "Arena de cama, arena de relleno y arena de juego no son iguales. La granulometria afecta drenaje, compactacion y rendimiento.",
      "Para adoquines, la arena de cama es una capa fina y uniforme. Una capa gruesa se mueve y causa asentamientos.",
      "La humedad cambia el peso por volumen. Si conviertes a toneladas, usa la conversion del proveedor para ese material.",
      "Pequenos errores en espesor cambian mucho el volumen, especialmente en areas grandes. Revisa unidades antes de ordenar.",
      "Un margen pequeno evita quedarte corto y reduce el riesgo de una segunda entrega.",
    ],
    howToMeasureTitle: "Como medir arena",
    howToMeasureSteps: [
      "Mide el area a cubrir.",
      "Define espesor objetivo (convertido a unidad consistente).",
      "Volumen = area x espesor.",
      "Convierte a yardas3 (pies3/27) o m3.",
      "Si compras en bolsas, divide por volumen por bolsa y redondea hacia arriba.",
      "Agrega margen por asentamiento y desperdicio.",
    ],
    assumptionsTitle: "Supuestos a revisar",
    assumptions: [
      "El tipo de arena afecta densidad y compactacion.",
      "Humedad cambia el peso si compras por tonelada.",
      "Espesor objetivo debe ser realista para el uso.",
      "Arena de cama es capa fina, no relleno grueso.",
      "Areas grandes amplifican errores de espesor.",
    ],
    buyingTipsTitle: "Consejos de compra",
    buyingTips: [
      "Confirma el tipo de arena recomendado para tu aplicacion.",
      "Si compras por peso, pide densidad o tabla de conversion del proveedor.",
      "Planifica entrega y acceso; la arena a granel ocupa mucho espacio.",
      "Compra un poco extra para ajustes finales.",
      "Para adoquines, compra tambien arena de juntas/polimerica si aplica.",
      "Revisa politica de devolucion si compras en bolsas.",
    ],
    commonMistakesTitle: "Errores comunes",
    commonMistakes: [
      "Usar arena equivocada para la aplicacion.",
      "Hacer capa de cama demasiado gruesa y causar asentamientos.",
      "Convertir a toneladas con una densidad generica incorrecta.",
      "Olvidar margen por desperdicio y quedar corto.",
      "Confundir unidades (pulgadas vs pies, m2 vs pies2).",
    ],
    lastUpdated: "Ultima actualizacion: ene 2026",
  },

  soilMix: {
    quick: [
      "Define tu receta (por ejemplo, tierra + compost + material de drenaje).",
      "Mide el volumen del cantero/cama elevada: largo x ancho x profundidad.",
      "Convierte a yardas3/m3 y divide en porcentajes segun la mezcla.",
      "Agrega margen por asentamiento y porque el material se compacta al regar.",
      "Si usas bolsas, convierte por volumen por bolsa, no por peso.",
      "Ajusta la mezcla al uso (huerto vs ornamentales) y al clima (segun caso).",
    ],
    deepDiveTitle: "Mezcla por volumen, no por peso",
    deepDive: [
      "Las recetas de soil mix funcionan mejor por volumen: '1/3 + 1/3 + 1/3' significa partes volumetricas. Los materiales tienen densidades distintas, asi que el peso confunde.",
      "En camas elevadas, la profundidad determina mucho el volumen. Revisa la profundidad real util (no solo la altura del borde).",
      "El material se asienta despues de riego y lluvia. Un margen pequeno evita tener que rellenar poco despues.",
      "El compost mejora retencion y nutrientes, pero demasiado puede retener agua en exceso. La proporcion ideal depende del suelo base y de las plantas (segun caso).",
      "Si mezclas en sitio, planifica espacio y metodo. Mezclar mal crea zonas con distinta textura y drenaje.",
    ],
    howToMeasureTitle: "Como medir una mezcla de suelo",
    howToMeasureSteps: [
      "Mide largo, ancho y profundidad de la cama/cantero.",
      "Volumen = largo x ancho x profundidad (unidades consistentes).",
      "Convierte a yardas3 o m3 para pedidos a granel.",
      "Aplica porcentajes de mezcla para cada componente (por volumen).",
      "Convierte cada componente a bolsas si aplica y redondea hacia arriba.",
      "Agrega margen por asentamiento y variacion en profundidad.",
    ],
    assumptionsTitle: "Supuestos a revisar",
    assumptions: [
      "Las proporciones son por volumen, no por peso.",
      "La profundidad util puede ser menor por drenaje o capas.",
      "Los materiales se asientan tras riego/lluvia.",
      "El componente de drenaje depende del clima y del tipo de planta.",
      "Bolsas se convierten por volumen, no por peso.",
    ],
    buyingTipsTitle: "Consejos de compra",
    buyingTips: [
      "Compra materiales de calidad consistente (tierra cernida, compost maduro).",
      "Si el uso es huerto, evita mezclas con demasiada madera sin compostar.",
      "Planifica entrega y espacio para mezclar.",
      "Compra un poco extra para rellenar despues del asentamiento.",
      "Anota la receta para poder replicarla en futuras expansiones.",
      "Si dudas, consulta recomendaciones locales para tu clima y plantas.",
    ],
    commonMistakesTitle: "Errores comunes",
    commonMistakes: [
      "Mezclar por peso y terminar con proporciones equivocadas.",
      "Usar la altura total del borde como profundidad util.",
      "No dejar margen y tener que rellenar a los pocos dias.",
      "Usar compost inmaduro y afectar plantas.",
      "No mezclar bien y crear zonas con drenaje desigual.",
    ],
    lastUpdated: "Ultima actualizacion: ene 2026",
  },

  asphaltDriveway: {
    quick: [
      "Mide largo x ancho de la entrada y define espesor compacto objetivo.",
      "Estima por capas: base granular + asfalto. No mezcles todo en un solo espesor.",
      "Convierte volumen a toneladas usando densidad del proveedor (varia por mezcla).",
      "Agrega margen por compactacion, desperdicio y bordes.",
      "Verifica si necesitas mas espesor por cargas (camionetas, RVs) (segun caso).",
      "Planifica drenaje: la pendiente manda tanto como el espesor.",
    ],
    deepDiveTitle: "Espesor, compactacion y base determinan durabilidad",
    deepDive: [
      "El asfalto se compra a menudo por toneladas. La conversion desde volumen depende de densidad y del tipo de mezcla; usar la cifra del proveedor es lo mas fiable.",
      "El espesor final suele ser compactado. Si pides material para el espesor final sin considerar compactacion y perdidas, puedes quedarte corto.",
      "La base es critica. Un buen espesor de asfalto sobre una base mala falla rapido. Planifica base, drenaje y compactacion en conjunto.",
      "Los bordes y transiciones consumen material extra. En obras reales, el area no es un rectangulo perfecto.",
      "Cargas pesadas requieren diseno distinto. El espesor recomendado depende del uso y del suelo (segun caso).",
    ],
    howToMeasureTitle: "Como medir asfalto para una entrada",
    howToMeasureSteps: [
      "Mide el area: largo x ancho y suma secciones.",
      "Define espesor compacto final de asfalto.",
      "Volumen = area x espesor (unidades consistentes).",
      "Convierte a toneladas usando densidad del proveedor.",
      "Agrega margen por bordes, desperdicio y compactacion.",
      "Si hay base granular, estima esa capa aparte.",
    ],
    assumptionsTitle: "Supuestos a revisar",
    assumptions: [
      "La densidad del asfalto depende de la mezcla y del proveedor.",
      "Espesor final es compactado; material suelto se compacta.",
      "La base y el drenaje afectan la vida util.",
      "Bordes y transiciones requieren margen.",
      "Cargas pesadas pueden requerir mas espesor (segun caso).",
    ],
    buyingTipsTitle: "Consejos de compra",
    buyingTips: [
      "Pide al proveedor conversion de volumen a toneladas para la mezcla exacta.",
      "Confirma espesores recomendados para tu uso y clima.",
      "Planifica compactacion y numero de pasadas del rodillo.",
      "Incluye material de base y reparacion de subrasante si es necesario.",
      "Compra margen para evitar juntas frias o parches por falta de mezcla.",
      "Verifica accesos y programacion: el asfalto se trabaja caliente y con tiempo limitado.",
    ],
    commonMistakesTitle: "Errores comunes",
    commonMistakes: [
      "Convertir a toneladas con una densidad generica incorrecta.",
      "Subestimar compactacion y quedarte corto.",
      "Ignorar base y drenaje y depender solo del espesor de asfalto.",
      "No agregar margen para bordes y formas irregulares.",
      "Planificar mal la logistica y tener mezcla que se enfria antes de compactar.",
    ],
    lastUpdated: "Ultima actualizacion: ene 2026",
  },

  boardFeet: {
    quick: [
      "Mide espesor, ancho y largo de cada pieza de madera.",
      "Convierte a board feet y suma todas las piezas.",
      "Verifica unidades: pulgadas para espesor/ancho y pies para largo (o convierte antes).",
      "Agrega desperdicio por cortes, defectos y seleccion de veta (segun proyecto).",
      "Si compras madera rough, considera perdida por cepillado y escuadrado.",
      "Redondea a una compra practica segun como vende tu proveedor.",
    ],
    deepDiveTitle: "Board feet es volumen estandarizado",
    deepDive: [
      "Un board foot es el volumen de una tabla de 1\" x 12\" x 12\". Es un estandar comun para maderas duras y algunas compras por volumen.",
      "El error mas comun es mezclar unidades: largo en pulgadas o metros sin convertir, o usar medidas nominales en vez de reales.",
      "El desperdicio viene de nudos, grietas, arqueo y de la orientacion de la veta. Proyectos finos requieren mas seleccion (segun caso).",
      "Si la madera es rough-sawn, parte del volumen se pierde al cepillar a espesor final y al escuadrar cantos.",
      "La conversion a board feet ayuda a comparar precios entre especies y dimensiones, incluso si el proveedor vende por pieza.",
    ],
    howToMeasureTitle: "Como calcular board feet",
    howToMeasureSteps: [
      "Anota espesor (in), ancho (in) y largo (ft) de cada pieza.",
      "Board feet por pieza = (espesor x ancho x largo) / 12.",
      "Suma todas las piezas para total de board feet.",
      "Convierte unidades si mides en cm o metros antes de aplicar la formula.",
      "Agrega un porcentaje de desperdicio segun cortes y calidad requerida.",
      "Redondea a longitudes/anchos estandar disponibles.",
    ],
    assumptionsTitle: "Supuestos a revisar",
    assumptions: [
      "La formula usa pulgadas y pies (a menos que conviertas antes).",
      "Medidas nominales pueden diferir de medidas reales.",
      "Madera rough requiere margen por cepillado.",
      "Seleccion de calidad y veta cambia desperdicio.",
      "Disponibilidad de longitudes estandar puede forzar cortes adicionales.",
    ],
    buyingTipsTitle: "Consejos de compra",
    buyingTips: [
      "Confirma si el proveedor usa medidas nominales o reales para precio.",
      "Compra un poco extra si necesitas emparejar color/veta.",
      "Si necesitas tableros largos, compra longitudes mayores para evitar empalmes.",
      "Para madera rough, compra mas para cubrir perdida por cepillado.",
      "Almacena madera en lugar seco para evitar deformacion.",
      "Lleva una lista por dimensiones para comparar costo por board foot.",
    ],
    commonMistakesTitle: "Errores comunes",
    commonMistakes: [
      "Mezclar pulgadas, pies y metros sin convertir.",
      "Asumir que nominal = real y comprar poco.",
      "No agregar desperdicio por defectos y seleccion.",
      "Olvidar perdida por cepillado en madera rough.",
      "Comprar longitudes exactas sin margen para cortes limpios.",
    ],
    lastUpdated: "Ultima actualizacion: ene 2026",
  },

  mulchBags: {
    quick: [
      "Mide el area de la cama y define la profundidad objetivo.",
      "Convierte profundidad a unidad consistente (pulgadas a pies).",
      "Volumen = area x profundidad, luego divide por volumen por bolsa.",
      "Las bolsas se etiquetan por volumen (pies3 o litros), no por peso.",
      "Agrega margen por asentamiento y distribucion irregular.",
      "Redondea hacia arriba a bolsas completas para terminar en una sola compra.",
    ],
    deepDiveTitle: "Bolsas = volumen etiquetado",
    deepDive: [
      "Para estimar bolsas, usa el volumen de la bolsa en la etiqueta. El peso no es un buen sustituto del volumen.",
      "La profundidad manda: pasar de 2\" a 3\" es 50% mas volumen. Revisa el numero antes de comprar muchas bolsas.",
      "El mulch se asienta despues de lluvia y rastrillado. Un margen pequeno evita zonas delgadas.",
      "Si solo renuevas, a menudo no necesitas cubrir todo a profundidad completa. Puedes enfocar zonas ralas y bordes.",
      "Comprar todo a la vez ayuda con consistencia de color.",
    ],
    howToMeasureTitle: "Como calcular bolsas de mulch",
    howToMeasureSteps: [
      "Mide el area total a cubrir.",
      "Elige profundidad objetivo y conviertela a pies (in/12).",
      "Calcula volumen total en pies3: area (pies2) x profundidad (pies).",
      "Divide por volumen por bolsa (pies3 por bolsa).",
      "Agrega margen por asentamiento y desperdicio.",
      "Redondea hacia arriba a bolsas completas.",
    ],
    assumptionsTitle: "Supuestos a revisar",
    assumptions: [
      "La bolsa se convierte por volumen (pies3/litros), no por peso.",
      "La profundidad objetivo debe ser realista para el objetivo.",
      "El mulch se asienta y puede requerir ajuste.",
      "No se debe apilar contra troncos o coronas de plantas.",
      "Color/lote puede variar entre compras separadas.",
    ],
    buyingTipsTitle: "Consejos de compra",
    buyingTips: [
      "Lee la etiqueta: volumen por bolsa y tipo de mulch.",
      "Compra un poco extra para retoques y zonas delgadas.",
      "Compra todo a la vez si el color importa.",
      "Si el volumen es grande, compara costo a granel vs bolsas.",
      "Planea transporte y manejo: las bolsas son trabajo intensivo.",
      "Mantén bolsas cubiertas si hay lluvia para facilitar aplicacion.",
    ],
    commonMistakesTitle: "Errores comunes",
    commonMistakes: [
      "Convertir por peso en vez de por volumen.",
      "Confundir pulgadas con pies y subestimar o sobreestimar.",
      "No considerar asentamiento y quedar con cobertura delgada.",
      "Apilar contra troncos y causar problemas de humedad.",
      "Comprar en lotes distintos y notar diferencia de color.",
    ],
    lastUpdated: "Ultima actualizacion: ene 2026",
  },

  concreteBags: {
    quick: [
      "Mide largo x ancho y espesor de la losa (o volumen de un hoyo/poste).",
      "Convierte a volumen y luego a numero de bolsas segun rendimiento por bolsa.",
      "El rendimiento depende del peso de la bolsa (40/60/80 lb) o kg y del producto.",
      "Agrega margen por desperdicio y porque el volumen real rara vez es perfecto.",
      "Si hay varios vertidos (losa + escalon + zapata), estima cada uno por separado.",
      "Redondea hacia arriba: quedarte corto a mitad de mezcla es un problema.",
    ],
    deepDiveTitle: "El rendimiento por bolsa es la clave",
    deepDive: [
      "Las bolsas de concreto tienen rendimientos distintos segun el peso y el producto. Usa la tabla del fabricante para el tipo de bolsa que compras.",
      "El volumen real puede subir por sobreexcavacion, bordes irregulares y material que se queda en carretilla/herramientas. Un margen pequeno ayuda a terminar.",
      "Para postes y hoyos, el diametro y profundidad suelen variar. Medir varios y usar un promedio puede ser mas realista que asumir un cilindro perfecto.",
      "Si necesitas muchos sacos, compara con concreto premezclado por entrega: puede ahorrar tiempo y dar mejor consistencia (segun volumen y acceso).",
      "Planifica agua y mezcla: demasiada agua debilita el concreto. Consistencia correcta mejora resistencia y acabado.",
    ],
    howToMeasureTitle: "Como calcular bolsas de concreto",
    howToMeasureSteps: [
      "Calcula volumen del proyecto (losa: area x espesor; hoyo: volumen de cilindro).",
      "Convierte unidades para tener volumen en pies3 o m3.",
      "Usa rendimiento por bolsa del producto (pies3 por bolsa) para convertir a bolsas.",
      "Bolsas = volumen total / rendimiento por bolsa.",
      "Agrega margen por desperdicio y variaciones en excavacion.",
      "Redondea hacia arriba y planifica el orden de mezcla para trabajar sin pausas largas.",
    ],
    assumptionsTitle: "Supuestos a revisar",
    assumptions: [
      "Rendimiento depende de peso de bolsa y del producto.",
      "Volumen real puede variar por excavacion y formas irregulares.",
      "Desperdicio y limpieza consumen mezcla.",
      "Mezclar demasiada agua cambia resistencia.",
      "A grandes volumenes, premezclado puede ser mejor opcion (segun caso).",
    ],
    buyingTipsTitle: "Consejos de compra",
    buyingTips: [
      "Compra bolsas del mismo tipo/peso para consistencia de rendimiento.",
      "Compra un poco extra para no quedarte corto.",
      "Planifica mezcladora o equipo si son muchas bolsas.",
      "Ten agua medida y herramientas listas antes de mezclar.",
      "Verifica tiempo de trabajo y clima: calor acelera fraguado.",
      "Si la obra es grande, compara costo con entrega de ready-mix.",
    ],
    commonMistakesTitle: "Errores comunes",
    commonMistakes: [
      "Usar un rendimiento equivocado (peso de bolsa distinto).",
      "No agregar margen y quedarse corto.",
      "Agregar demasiada agua para facilitar mezcla y debilitar el concreto.",
      "No planificar el ritmo de mezcla y crear juntas frias.",
      "Subestimar volumen en hoyos irregulares.",
    ],
    lastUpdated: "Ultima actualizacion: ene 2026",
  },

  studs: {
    quick: [
      "Empieza por la longitud total de paredes y el espaciado de montantes (16\" o 24\" OC son comunes).",
      "Puertas y ventanas agregan madera: montantes king/jack y soportes no salen del calculo simple.",
      "Define la altura de muro (8/9/10 ft) para elegir longitudes de madera (92 5/8\", 104 5/8\", etc.).",
      "Agrega margen por piezas torcidas, cortes y cambios de diseno (5-10% suele ser razonable).",
      "Esquinas y encuentros en T pueden duplicar montantes segun el metodo de enmarcado.",
      "Si necesitas refuerzos (blocking) para gabinetes, barandales o TV, planifica madera extra.",
    ],
    deepDiveTitle: "El conteo real depende de esquinas y aberturas",
    deepDive: [
      "Dividir longitud entre espaciado te da un estimado base, pero el enmarcado real incluye mas madera en esquinas, encuentros y aberturas.",
      "Las aberturas consumen montantes adicionales: king studs, jack studs, refuerzo para el marco y, a veces, montantes dobles segun carga y codigo (segun el caso).",
      "El espaciado es una decision estructural y de acabado. 16\" OC suele dar mas rigidez y soporte para paneles; 24\" OC puede reducir madera, pero no siempre es apropiado.",
      "La altura del muro cambia lo que compras. En vez de cortar 8 ft exactos, muchos usan longitudes estandar (92 5/8\", 104 5/8\") para muros con placa superior/inferior.",
      "Si el muro es exterior o en contacto con humedad, puede requerir madera tratada en placa inferior y detalles de barrera/aislamiento que no cambian el conteo de montantes, pero si el BOM.",
    ],
    howToMeasureTitle: "Como estimar montantes (studs)",
    howToMeasureSteps: [
      "Suma la longitud de cada tramo de muro que vas a enmarcar.",
      "Elige el espaciado (16\" o 24\" OC) segun diseno y requisitos locales.",
      "Calcula montantes base por tramo y redondea hacia arriba.",
      "Agrega montantes extra por esquinas, encuentros en T y aberturas (puertas/ventanas).",
      "Incluye margen por desperdicio y por piezas defectuosas o torcidas.",
      "Verifica alturas para elegir longitudes correctas y evitar cortes innecesarios.",
    ],
    assumptionsTitle: "Supuestos a revisar",
    assumptions: [
      "El espaciado OC elegido es compatible con tu codigo y cargas.",
      "Aberturas y esquinas agregan montantes adicionales mas alla del calculo base.",
      "La altura real incluye placas superior/inferior y puede cambiar la longitud comprada.",
      "Necesidades de backing/blocking no siempre estan incluidas en un estimado simple.",
      "El factor de desperdicio depende de la calidad de la madera y del diseno.",
    ],
    buyingTipsTitle: "Consejos de compra",
    buyingTips: [
      "Compra algunas piezas extra para seleccionar montantes rectos (especialmente para muros visibles).",
      "Verifica longitudes estandar que reducen cortes (92 5/8\", 104 5/8\", 116 5/8\").",
      "Si hay humedad, considera placa inferior tratada y fijaciones adecuadas.",
      "Incluye placas (top/bottom plates) y tornilleria/clavos en el plan de materiales.",
      "Si tienes muchas aberturas, planifica madera adicional para refuerzos y detalles.",
    ],
    commonMistakesTitle: "Errores comunes",
    commonMistakes: [
      "Olvidar montantes extra en esquinas, encuentros y aberturas.",
      "Mezclar 16\" y 24\" OC sin ajustar el conteo y el soporte de paneles.",
      "Comprar la longitud equivocada y terminar cortando demasiado material.",
      "No agregar margen y quedarte corto por madera torcida o danada.",
      "Ignorar blocking/backing requerido para gabinetes o accesorios pesados.",
    ],
    lastUpdated: "Ultima actualizacion: ene 2026",
  },

  baseboardTrim: {
    quick: [
      "Mide el perimetro de cada cuarto y resta puertas donde no va zocalo.",
      "Agrega margen por cortes en inglete, uniones y piezas con defectos.",
      "Cuenta esquinas internas/externas: aumentan cortes y desperdicio.",
      "Si usas zocalo alto o perfil complejo, planifica mas margen para empalmes limpios.",
      "Considera piezas especiales (retornos, tapas, esquineros) segun el estilo.",
      "Redondea a barras completas (8/12/16 ft) para reducir juntas visibles.",
    ],
    deepDiveTitle: "Las puertas y las esquinas cambian el metraje",
    deepDive: [
      "El calculo mas confiable es perimetro menos vanos de puerta. No intentes adivinar por area del piso: el perimetro manda.",
      "El desperdicio viene de ingletes y de la logistica de longitudes. Si el cuarto tiene paredes largas, comprar piezas mas largas puede reducir juntas.",
      "Perfiles pintables (MDF, finger-joint) vs madera natural: la eleccion afecta empalmes, acabado y tolerancia a golpes/humedad (segun el caso).",
      "Las paredes rara vez son perfectamente rectas. Puedes necesitar mas material para ajustar curvas leves, esquinas fuera de escuadra o transiciones.",
      "Planifica tambien el material de terminacion: masilla, clavos, calafateo y pintura. No cambia el metraje, pero afecta el trabajo final.",
    ],
    howToMeasureTitle: "Como medir zocalos (baseboard)",
    howToMeasureSteps: [
      "Mide largo de cada pared donde ira zocalo y suma.",
      "Resta el ancho de cada puerta (y otros vanos donde no se instala).",
      "Agrega margen por ingletes, empalmes y cortes (segun complejidad).",
      "Redondea a la longitud comercial de barras (8/12/16 ft) y planifica donde iran las juntas.",
      "Si hay escaleras o pasillos con cambios, mide esos tramos por separado.",
    ],
    assumptionsTitle: "Supuestos a revisar",
    assumptions: [
      "No se instala zocalo a traves de puertas (se resta el vano).",
      "El desperdicio depende de esquinas, longitud de barras y empalmes visibles.",
      "Paredes fuera de escuadra pueden aumentar cortes y desperdicio.",
      "El material elegido (MDF/madera) afecta tolerancia a humedad y golpes.",
      "Transiciones y retornos pueden requerir piezas extra (segun diseno).",
    ],
    buyingTipsTitle: "Consejos de compra",
    buyingTips: [
      "Compra barras mas largas si quieres menos juntas en paredes principales.",
      "Compra un poco extra para reparaciones futuras y para seleccionar piezas rectas.",
      "En banos o zonas humedas, evita MDF comun o usa materiales resistentes a humedad.",
      "Incluye esquinas/retornos prehechos si tu perfil los requiere.",
      "Verifica si el perfil viene preimprimado o preacabado para ahorrar tiempo.",
    ],
    commonMistakesTitle: "Errores comunes",
    commonMistakes: [
      "Olvidar restar puertas y comprar de mas (o medir mal y quedarte corto).",
      "No agregar margen para ingletes y empalmes.",
      "Comprar solo piezas cortas y terminar con demasiadas juntas visibles.",
      "Instalar MDF en zonas humedas y ver hinchazon con el tiempo.",
      "No planificar transiciones y retornos en extremos expuestos.",
    ],
    lastUpdated: "Ultima actualizacion: ene 2026",
  },

  topsoilBags: {
    quick: [
      "Mide el area a cubrir (largo x ancho) y define la profundidad objetivo.",
      "Convierte la profundidad a pies (in/12) o metros (cm/100) para calcular volumen.",
      "Volumen = area x profundidad; luego convierte a bolsas segun volumen por bolsa (cu ft o L).",
      "Redondea hacia arriba a bolsas completas y agrega margen por asentamiento y nivelacion.",
      "No uses solo peso de la bolsa para estimar volumen: revisa el volumen declarado.",
      "Si el terreno es irregular, usa un espesor promedio y considera extra para rellenos.",
    ],
    deepDiveTitle: "Las bolsas se calculan por volumen, no por peso",
    deepDive: [
      "La tierra en bolsa se vende con un volumen (por ejemplo 1 cu ft, 1.5 cu ft o litros). El peso cambia con humedad, asi que el volumen es la base correcta para estimar.",
      "El asentamiento es real: al regar y compactar ligeramente, el nivel baja. Si quieres un acabado nivelado, un margen pequeno evita tener que comprar mas al final.",
      "Para resiembra o top dressing de cesped, las profundidades son pequenas; en esas situaciones, errores de unidad (in vs ft) pueden multiplicar bolsas por 12.",
      "Si vas a mezclar tierra con compost u otros materiales, estima el volumen total y luego reparte por porcentaje. Mezclar por peso suele dar proporciones raras porque densidades difieren.",
      "En superficies con pendiente, el volumen depende del espesor promedio (espesor del borde alto + borde bajo) / 2.",
    ],
    howToMeasureTitle: "Como calcular bolsas de topsoil",
    howToMeasureSteps: [
      "Mide el area en pies2 o m2 (divide formas complejas en rectangulos y suma).",
      "Elige la profundidad y conviertela a pies o metros.",
      "Volumen = area x profundidad (cu ft o m3).",
      "Convierte a bolsas: bolsas = volumen total / volumen por bolsa.",
      "Redondea hacia arriba y agrega margen por asentamiento y perdidas.",
      "Si compras varios tamanos de bolsa, calcula por tipo y suma.",
    ],
    assumptionsTitle: "Supuestos a revisar",
    assumptions: [
      "Profundidad es un promedio realista; irregularidades cambian volumen.",
      "El volumen por bolsa es el indicado en la etiqueta (no el peso).",
      "Habra asentamiento despues de regar/compactar.",
      "Se excluyen zonas que no recibiran tierra (bordes, pavimento, rocas).",
      "En pendientes, se usa espesor promedio y no el mas alto.",
    ],
    buyingTipsTitle: "Consejos de compra",
    buyingTips: [
      "Confirma volumen por bolsa y compara costo por cu ft (o L).",
      "Compra un poco extra si necesitas un acabado nivelado o si el terreno esta bajo.",
      "Si el volumen es grande, compara con entrega a granel (puede ser mas barato).",
      "Evita tierra demasiado mojada o con muchos palos; calidad varía por proveedor.",
      "Planifica herramientas y transporte: mover muchas bolsas consume tiempo.",
    ],
    commonMistakesTitle: "Errores comunes",
    commonMistakes: [
      "Confundir pulgadas con pies al convertir profundidad.",
      "Usar peso de la bolsa como si fuera volumen.",
      "No considerar asentamiento y quedarse corto.",
      "No excluir areas que no se cubren y comprar de mas.",
      "Usar densidad generica y esperar un numero exacto de bolsas: la realidad varia.",
    ],
    lastUpdated: "Ultima actualizacion: ene 2026",
  },

  gravelTons: {
    quick: [
      "Mide el area y define el espesor compactado objetivo (no el espesor suelto).",
      "Convierte a volumen (cu yd o m3) y luego a toneladas segun densidad realista.",
      "La densidad cambia por tipo de piedra, humedad y compactacion: confirma con proveedor.",
      "Agrega margen por bordes, irregularidades y variacion de espesor (5-10% suele ayudar).",
      "Si hay base y capa superior, estima cada capa por separado y suma.",
      "En pendientes, usa espesor promedio para no subestimar.",
    ],
    deepDiveTitle: "Toneladas dependen de densidad y compactacion",
    deepDive: [
      "El calculo empieza por volumen (area x espesor). La conversion a toneladas depende de densidad, que varía entre grava, triturado, pea gravel, y materiales con finos.",
      "La compactacion importa: el espesor objetivo suele ser despues de compactar. Si calculas con espesor suelto, puedes quedarte corto una vez compactado.",
      "La humedad cambia el peso. Material mojado puede pesar mas por la misma cantidad de volumen, por eso la conversion del proveedor suele ser mas confiable que una tabla generica.",
      "Los bordes y transiciones consumen material: si el area no es un rectangulo perfecto, el margen evita viajes extra.",
      "Para entradas de autos o bases de adoquin, la calidad de subbase y drenaje influye mas en el resultado que afinar decimales en toneladas (segun el caso).",
    ],
    howToMeasureTitle: "Como estimar grava en toneladas",
    howToMeasureSteps: [
      "Mide el area total (pies2 o m2). Divide curvas en formas simples.",
      "Elige espesor compactado y conviertelo a pies o metros.",
      "Volumen = area x espesor (cu ft o m3).",
      "Convierte a cu yd si lo necesitas (cu ft / 27).",
      "Usa una densidad/ratio de conversion recomendado por tu proveedor para convertir a toneladas.",
      "Agrega margen por variacion de espesor, bordes e irregularidades.",
    ],
    assumptionsTitle: "Supuestos a revisar",
    assumptions: [
      "El espesor objetivo es despues de compactar.",
      "La densidad usada corresponde al tipo de grava real y a su humedad.",
      "El area medida incluye solo donde se colocara material.",
      "Hay perdidas por esparcido y nivelacion.",
      "Capas multiples se estiman por separado (base vs capa final).",
    ],
    buyingTipsTitle: "Consejos de compra",
    buyingTips: [
      "Pide al proveedor conversion cu yd -> toneladas para el material especifico.",
      "Confirma si el precio es por tonelada, por yarda o por camion.",
      "Planifica el acceso del camion y el lugar de descarga para minimizar trabajo manual.",
      "Compra un poco extra para ajustes finales y rellenos.",
      "Si necesitas compactacion, incluye renta de compactador y tiempo de capas.",
    ],
    commonMistakesTitle: "Errores comunes",
    commonMistakes: [
      "Usar densidad generica y sorprenderse con el peso real.",
      "Calcular con espesor suelto y quedarse corto tras compactar.",
      "Confundir cu ft con cu yd (factor 27).",
      "No agregar margen para bordes e irregularidades.",
      "No separar capas (base y acabado) y mezclar espesores.",
    ],
    lastUpdated: "Ultima actualizacion: ene 2026",
  },

  tileGrout: {
    quick: [
      "Mide el area total a instalar (pies2 o m2) y resta huecos grandes si quieres afinar.",
      "Confirma tamano de baldosa, ancho de junta y espesor: esos tres mandan el consumo.",
      "Elige tipo de boquilla (sanded/unsanded/epoxy) segun ancho de junta y uso.",
      "Usa la tabla de cobertura del fabricante para convertir area a bolsas (las formulas genericas fallan).",
      "Agrega margen por desperdicio, mezcla que se endurece y limpieza (especialmente para principiantes).",
      "Si hay muchas piezas pequenas o mosaico, el consumo sube por mas juntas por area.",
    ],
    deepDiveTitle: "La cobertura cambia por junta y formato de baldosa",
    deepDive: [
      "El grout llena volumen de juntas, no area. Por eso, juntas mas anchas o baldosas mas pequenas aumentan consumo de forma significativa.",
      "La cobertura depende del producto: hay grout con arenas finas, sin arena, polimerico o epoxi. Cada uno tiene densidad y rendimiento distinto.",
      "La profundidad de junta suele ser el espesor de la baldosa menos el espesor de thinset bajo la pieza. En la practica, la junta no siempre se llena 100% uniforme, por eso un margen ayuda.",
      "El desperdicio es real: parte se queda en cubeta, flotador y esponja, y parte se pierde por tiempos de trabajo (batch que fragua).",
      "Si buscas color uniforme, comprar todo del mismo lote reduce variacion. Mezclar lotes o marcas distintas puede notarse (segun color).",
    ],
    howToMeasureTitle: "Como estimar bolsas de grout",
    howToMeasureSteps: [
      "Mide el area total a instalar y define si restaras aberturas grandes.",
      "Anota el tamano de baldosa (largo x ancho), el ancho de junta y el espesor.",
      "Elige el producto exacto de grout y busca su tabla de cobertura.",
      "Convierte area a bolsas segun la cobertura del fabricante.",
      "Redondea hacia arriba y agrega margen por desperdicio y ritmo de trabajo.",
      "Si hay zonas con junta distinta (pared vs piso), calcula por separado y suma.",
    ],
    assumptionsTitle: "Supuestos a revisar",
    assumptions: [
      "El producto elegido coincide con el ancho de junta (sanded vs unsanded, etc.).",
      "La junta se llena a una profundidad consistente (aprox).",
      "El formato de baldosa y el ancho de junta son los reales de instalacion.",
      "Se considera desperdicio por mezcla, limpieza y herramientas.",
      "Cobertura del fabricante es para ese producto especifico y condiciones normales.",
    ],
    buyingTipsTitle: "Consejos de compra",
    buyingTips: [
      "Compra todo del mismo lote si el color es importante.",
      "Si no estas seguro del color, compra una muestra o un saco pequeno primero.",
      "Ten sellador o aditivo si tu sistema lo requiere (segun grout).",
      "Planea herramientas: flotador, esponjas, cubetas, agua limpia, mezclador.",
      "Si el area es grande, compra extra para no quedarte corto entre lotes.",
    ],
    commonMistakesTitle: "Errores comunes",
    commonMistakes: [
      "Elegir grout equivocado para el ancho de junta y ver grietas o manchas.",
      "No seguir proporciones de agua y cambiar consistencia entre lotes.",
      "No considerar mosaicos/piezas pequenas y quedarse corto.",
      "Confiar en una formula generica en vez de la tabla del fabricante.",
      "Mezclar demasiado a la vez y perder material por fraguado.",
    ],
    lastUpdated: "Ultima actualizacion: ene 2026",
  },

  drywallMudTape: {
    quick: [
      "El consumo depende de cuantas juntas y esquinas tienes, no solo de area.",
      "Cuenta laminas de drywall y estima lineas de junta (verticales/horizontales) segun layout.",
      "Decide el nivel de acabado (Level 3/4/5): mas nivel = mas compuesto y lijado.",
      "Las esquinas (internas/externas) consumen cinta y mas compuesto por pasada.",
      "Usa la cobertura por galon/bolsa del producto y agrega margen por desperdicio y lijado.",
      "Si hay textura pesada, el nivel de acabado puede bajar; si va liso y pintado, suele subir (segun objetivo).",
    ],
    deepDiveTitle: "Juntas, esquinas y nivel definen la cantidad",
    deepDive: [
      "Una habitacion con la misma area puede requerir cantidades muy distintas segun el numero de juntas, altura y cantidad de cortes.",
      "Butt joints (uniones de extremo) suelen requerir mas compuesto para difuminar y evitar que se note. Layout inteligente puede reducirlas.",
      "El tipo de cinta (papel vs malla) cambia el consumo y la tecnica. Papel suele ser mas fuerte en esquinas; malla es mas rapida pero puede requerir compuesto especifico (segun sistema).",
      "Nivel 4 suele implicar varias manos sobre juntas y tornillos. Nivel 5 agrega skim coat completo, aumentando material de forma marcada.",
      "Parte del material se pierde en la bandeja, en lijado y en reparaciones. Un margen ayuda a terminar sin parar.",
    ],
    howToMeasureTitle: "Como estimar mud y tape",
    howToMeasureSteps: [
      "Cuenta cuantas laminas vas a instalar y su orientacion (vertical/horizontal).",
      "Estima longitud total de juntas (seams) y de esquinas internas/externas.",
      "Define el nivel de acabado y el numero de manos planeadas.",
      "Convierte longitud/area a cantidad usando la cobertura del compuesto que compraras.",
      "Calcula cinta por longitud (rollos) y agrega margen para desperdicio y parches.",
      "Redondea hacia arriba para no quedarte corto a mitad del acabado.",
    ],
    assumptionsTitle: "Supuestos a revisar",
    assumptions: [
      "El layout real (seams y butt joints) coincide con el estimado.",
      "El nivel de acabado definido es el objetivo final (textura vs liso).",
      "Tipo de cinta y compuesto son compatibles entre si.",
      "Hay desperdicio por lijado, herramientas y reparaciones.",
      "Altura de muros y cantidad de esquinas influyen mas que el area sola.",
    ],
    buyingTipsTitle: "Consejos de compra",
    buyingTips: [
      "Compra compuesto segun tu ritmo (premixed vs polvo) y condiciones de secado.",
      "Ten cinta suficiente para esquinas y parches: un rollo extra evita parar.",
      "Incluye esquineros (corner bead) y tornillos, no solo mud/tape.",
      "Si buscas acabado liso, considera compuesto de terminacion y herramientas de alisado.",
      "Planea polvo de lijado: proteccion, aspiracion y mas material para retoques.",
    ],
    commonMistakesTitle: "Errores comunes",
    commonMistakes: [
      "Calcular por area y olvidar longitud de juntas y esquinas.",
      "No planificar butt joints y terminar usando demasiado compuesto para disimular.",
      "Mezclar sistemas (malla con compuesto no compatible) y ver grietas.",
      "No dejar secar entre manos y arruinar el acabado.",
      "Comprar justo y quedarte sin cinta/compuesto antes de terminar.",
    ],
    lastUpdated: "Ultima actualizacion: ene 2026",
  },

  drywallTexture: {
    quick: [
      "Mide el area real a texturizar (paredes/techo) y define el tipo de textura.",
      "El consumo depende de la tecnica (knockdown, orange peel, popcorn) y del espesor aplicado.",
      "Pulverizar genera perdida por sobrepulverizacion; agrega margen si es spray.",
      "Usa rendimiento del producto (bolsa/cubeta) para convertir area a cantidad.",
      "Si reparas solo parches, compra mas de lo que parece: igualar textura siempre consume extra.",
      "En techos altos o con muchos recortes, el desperdicio y tiempo suben (segun caso).",
    ],
    deepDiveTitle: "La textura es espesor + tecnica (no solo area)",
    deepDive: [
      "Dos techos con la misma area pueden usar cantidades muy distintas si una textura es ligera y otra es pesada. El espesor aplicado manda.",
      "El metodo cambia el rendimiento: rodillo, tolva (hopper) o spray airless tienen perdidas distintas. Over-spray puede ser importante.",
      "La preparacion es clave: sellar imprimacion, reparar juntas y controlar absorcion mejora uniformidad y reduce re-trabajo.",
      "Para parches, igualar el patron suele requerir varias pasadas y pruebas. Esto puede duplicar el consumo respecto a un calculo por area simple.",
      "Si se va a pintar despues, algunas texturas requieren imprimacion/primer para uniformidad; eso no cambia textura, pero si el plan de materiales.",
    ],
    howToMeasureTitle: "Como estimar material de textura",
    howToMeasureSteps: [
      "Mide area total a texturizar (largo x alto para paredes; largo x ancho para techo).",
      "Define tipo de textura y metodo de aplicacion (spray/rodillo).",
      "Elige un producto especifico y revisa su rendimiento por bolsa/cubeta.",
      "Convierte area a cantidad segun rendimiento y espesor recomendado.",
      "Agrega margen por sobrepulverizacion, parches y retoques.",
      "Redondea hacia arriba para mantener consistencia de mezcla en todo el espacio.",
    ],
    assumptionsTitle: "Supuestos a revisar",
    assumptions: [
      "Tipo de textura y espesor objetivo estan definidos.",
      "El rendimiento del fabricante corresponde al metodo elegido.",
      "Hay perdida por sobrepulverizacion y limpieza de equipo.",
      "Las reparaciones y parches pueden requerir mas material.",
      "La superficie esta preparada (sellada) para evitar absorcion irregular.",
    ],
    buyingTipsTitle: "Consejos de compra",
    buyingTips: [
      "Compra el mismo producto/lote si toda el area debe verse igual.",
      "Si es spray, incluye boquillas, tolva y proteccion (plasticos/cinta).",
      "Planifica imprimacion si la superficie es nueva o muy porosa.",
      "Compra un poco extra para parches futuros: igualar textura meses despues es dificil.",
      "Si el techo es grande, prueba en un area pequena para confirmar patron y consumo.",
    ],
    commonMistakesTitle: "Errores comunes",
    commonMistakes: [
      "Calcular solo por area y no por tipo/espesor de textura.",
      "No agregar margen por over-spray y limpieza.",
      "Aplicar sin sellar y obtener textura desigual por absorcion.",
      "Mezclar lotes distintos y ver diferencias de color/patron.",
      "No hacer prueba previa y descubrir tarde que el patron no coincide.",
    ],
    lastUpdated: "Ultima actualizacion: ene 2026",
  },
};
